const ISCAP_2014_030_URL = 'https://www.archives.gov/declassification/iscap/pdf/2014-030';
const NSARCHIVE_BASE = 'https://nsarchive.gwu.edu';
const NSARCHIVE_BAY_OF_PIGS_2 = 'https://nsarchive2.gwu.edu/bayofpigs/press2.html';
const NSARCHIVE_BAY_OF_PIGS_3 = 'https://nsarchive2.gwu.edu/bayofpigs/press3.html';

const iscapPdf = (number) =>
  `https://www.archives.gov/files/declassification/iscap/pdf/2014-030-document-${number}-release-508-complete.pdf`;

const nsarchiveDocument = (path) => `${NSARCHIVE_BASE}${path}`;
const bayOfPigsPdf = (fileName) => `https://nsarchive2.gwu.edu/bayofpigs/${fileName}`;

const iscapDefaults = {
  source: 'ISCAP',
  repository: 'Interagency Security Classification Appeals Panel',
  collection: 'ISCAP Appeals Log',
  container: '2014-030: Laos, 1961',
  section: 'Laos',
  documentType: 'ISCAP release',
  url: ISCAP_2014_030_URL,
  officialUrl: ISCAP_2014_030_URL,
  topics: ['Laos', 'Asia', 'Intelligence', 'Defense'],
  sourceNote:
    'Released through ISCAP appeal 2014-030 for records located at the John F. Kennedy Presidential Library and Museum.',
};

const nsarchiveDefaults = {
  source: 'National Security Archive',
  repository: 'National Security Archive, George Washington University',
  collection: 'National Security Archive Virtual Reading Room',
  documentType: 'National Security Archive document',
  officialUrl: 'https://nsarchive.gwu.edu/virtual-reading-room',
  sourceNote: 'Document page and PDF hosted by the National Security Archive.',
};

const bayOfPigsDefaults = {
  ...nsarchiveDefaults,
  collection: 'Bay of Pigs: 40 Years After',
  container: 'Bay of Pigs 40th anniversary release',
  section: 'Cuba and Bay of Pigs',
  documentType: 'National Security Archive Bay of Pigs release',
  topics: ['Bay of Pigs', 'Cuba', 'Latin America', 'Intelligence', 'Defense'],
  sourceNote: 'Released on the National Security Archive Bay of Pigs 40th anniversary website.',
};

export const supplementalRecords = [
  {
    ...iscapDefaults,
    id: 'iscap-2014-030-doc-1',
    title: 'Letter to Chester Clifton from Allen Dulles',
    date: '1961-02-20',
    documentNumber: '2014-030-doc 1',
    dataUrl: iscapPdf(1),
    citation: 'ISCAP Appeal 2014-030, document 1. Letter to Chester Clifton from Allen Dulles, February 20, 1961.',
    summary: 'Declassified CIA-related correspondence from Allen Dulles to Brig. Gen. Chester V. Clifton concerning Laos and related regional policy.',
  },
  {
    ...iscapDefaults,
    id: 'iscap-2014-030-doc-2',
    title: 'Memo re: Chiang Ching-kuo and GRC',
    date: '1961-02-20',
    documentNumber: '2014-030-doc 2',
    dataUrl: iscapPdf(2),
    citation: 'ISCAP Appeal 2014-030, document 2. Memo re: Chiang Ching-kuo and GRC, February 20, 1961.',
    summary: 'Declassified memorandum concerning Chiang Ching-kuo, the Government of the Republic of China, and regional security questions tied to Laos policy.',
    topics: ['Laos', 'Asia', 'Intelligence', 'Defense', 'Diplomacy'],
  },
  {
    ...iscapDefaults,
    id: 'iscap-2014-030-doc-3',
    title: 'Memo to Director from Vientiane',
    date: '1961-03-20',
    documentNumber: '2014-030-doc 3',
    dataUrl: iscapPdf(3),
    citation: 'ISCAP Appeal 2014-030, document 3. Memo to Director from Vientiane, March 20, 1961.',
    summary: 'Declassified Vientiane-origin memorandum to the Director during the Kennedy administration Laos crisis.',
  },
  {
    ...iscapDefaults,
    id: 'iscap-2014-030-doc-4',
    title: 'Cable to Director from Vientiane',
    date: '1961-03-20',
    documentNumber: '2014-030-doc 4',
    dataUrl: iscapPdf(4),
    citation: 'ISCAP Appeal 2014-030, document 4. Cable to Director from Vientiane, March 20, 1961.',
    summary: 'Declassified cable from Vientiane to the Director concerning Laos in March 1961.',
  },
  {
    ...iscapDefaults,
    id: 'iscap-2014-030-doc-5',
    title: 'Cable',
    date: '',
    displayDate: 'Undated (1961)',
    documentNumber: '2014-030-doc 5',
    dataUrl: iscapPdf(5),
    citation: 'ISCAP Appeal 2014-030, document 5. Cable, undated.',
    summary: 'Undated cable released with the ISCAP 2014-030 Laos, 1961 appeal file.',
  },
  {
    ...iscapDefaults,
    id: 'iscap-2014-030-doc-6',
    title: 'Cable to Director from Bangkok',
    date: '1961-04-06',
    documentNumber: '2014-030-doc 6',
    dataUrl: iscapPdf(6),
    citation: 'ISCAP Appeal 2014-030, document 6. Cable to Director from Bangkok, April 6, 1961.',
    summary: 'Declassified Bangkok-origin cable to the Director concerning Laos and regional covert-action issues.',
    topics: ['Laos', 'Asia', 'Intelligence', 'Defense', 'Diplomacy'],
  },
  {
    ...bayOfPigsDefaults,
    id: 'nsarchive-bop-19610211-schlesinger',
    title: 'White House memorandum from Arthur Schlesinger, Jr. to President Kennedy',
    date: '1961-02-11',
    documentNumber: '19610211',
    url: NSARCHIVE_BAY_OF_PIGS_2,
    officialUrl: NSARCHIVE_BAY_OF_PIGS_2,
    dataUrl: bayOfPigsPdf('19610211.pdf'),
    citation: 'White House, Memorandum, Top Secret, Arthur Schlesinger, Jr. to President Kennedy, February 11, 1961.',
    summary: 'Schlesinger warned Kennedy about the political and diplomatic costs of a unilateral invasion of Cuba.',
  },
  {
    ...bayOfPigsDefaults,
    id: 'nsarchive-bop-19610406-cia-discontent',
    title: 'CIA information report on signs of discontent among the Cuban populace',
    date: '1961-04-06',
    documentNumber: '19610406',
    url: NSARCHIVE_BAY_OF_PIGS_3,
    officialUrl: NSARCHIVE_BAY_OF_PIGS_3,
    dataUrl: bayOfPigsPdf('19610406.pdf'),
    citation: 'CIA, Information Report, Signs of Discontent among the Cuban Populace; Activities of the Government to Strengthen Regime, April 6, 1961.',
    summary: 'CIA reporting assessed Cuban public attitudes and regime security activity in the days before the Bay of Pigs invasion.',
  },
  {
    ...bayOfPigsDefaults,
    id: 'nsarchive-bop-19610414-kudryavtsev-guevara-translation',
    title: 'Diary of S. M. Kudryavtsev, record of conversation with Ernesto Guevara (English translation)',
    date: '1961-04-14',
    documentNumber: '19610426-trans',
    url: NSARCHIVE_BAY_OF_PIGS_3,
    officialUrl: NSARCHIVE_BAY_OF_PIGS_3,
    dataUrl: bayOfPigsPdf('19610426-trans.pdf'),
    citation: 'Diary of S. M. Kudryavtsev, Record of Conversation with Ernesto Guevara, April 14, 1961, English translation.',
    summary: 'A Soviet ambassador recorded Che Guevara discussing Cuba, the expected U.S.-backed invasion, and Cuban expectations before the air strikes.',
    topics: ['Bay of Pigs', 'Cuba', 'Latin America', 'USSR', 'Diplomacy'],
  },
  {
    ...bayOfPigsDefaults,
    id: 'nsarchive-bop-19610414-kudryavtsev-guevara-original',
    title: 'Diary of S. M. Kudryavtsev, record of conversation with Ernesto Guevara (Russian original)',
    date: '1961-04-14',
    documentNumber: '19610426',
    url: NSARCHIVE_BAY_OF_PIGS_3,
    officialUrl: NSARCHIVE_BAY_OF_PIGS_3,
    dataUrl: bayOfPigsPdf('19610426.pdf'),
    citation: 'Diary of S. M. Kudryavtsev, Record of Conversation with Ernesto Guevara, April 14, 1961, Russian original.',
    summary: 'Russian-language original of the Kudryavtsev record of conversation with Ernesto Guevara before the Bay of Pigs invasion.',
    topics: ['Bay of Pigs', 'Cuba', 'Latin America', 'USSR', 'Diplomacy'],
  },
  {
    ...bayOfPigsDefaults,
    id: 'nsarchive-bop-196104-chart-plans-training',
    title: 'CIA chart of command organization for plans and training',
    date: '1961-04-01',
    displayDate: 'ca. April 1961',
    documentNumber: 'chart1',
    url: NSARCHIVE_BAY_OF_PIGS_3,
    officialUrl: NSARCHIVE_BAY_OF_PIGS_3,
    dataUrl: bayOfPigsPdf('chart1.pdf'),
    citation: 'CIA, Chart, Secret, Chart of Command Organization for Plans and Training, ca. April 1961.',
    summary: 'Organizational chart for the CIA task force planning and training structure behind the Cuba operation.',
  },
  {
    ...bayOfPigsDefaults,
    id: 'nsarchive-bop-196104-chart-operations',
    title: 'CIA chart of command organization for operations',
    date: '1961-04-01',
    displayDate: 'ca. April 1961',
    documentNumber: 'chart2',
    url: NSARCHIVE_BAY_OF_PIGS_3,
    officialUrl: NSARCHIVE_BAY_OF_PIGS_3,
    dataUrl: bayOfPigsPdf('chart2.pdf'),
    citation: 'CIA, Chart, Secret, Chart of Command Organization for Operations, ca. April 1961.',
    summary: 'Organizational chart for operational command relationships in the CIA-backed Cuba operation.',
  },
  {
    ...bayOfPigsDefaults,
    id: 'nsarchive-bop-19610417-castro-order-translation',
    title: 'Handwritten order from Fidel Castro to Captain Jose R. Fernandez (translation)',
    date: '1961-04-17',
    documentNumber: '19610417-trans',
    url: NSARCHIVE_BAY_OF_PIGS_3,
    officialUrl: NSARCHIVE_BAY_OF_PIGS_3,
    dataUrl: bayOfPigsPdf('19610417-trans.pdf'),
    citation: 'Handwritten Order from Commander-in-Chief Fidel Castro to Captain Jose R. Fernandez, April 17, 1961, English translation.',
    summary: 'Translated Castro battlefield order during the opening day of the Bay of Pigs invasion.',
  },
  {
    ...bayOfPigsDefaults,
    id: 'nsarchive-bop-19610417-castro-order-original',
    title: 'Handwritten order from Fidel Castro to Captain Jose R. Fernandez (Spanish original)',
    date: '1961-04-17',
    documentNumber: '19610417',
    url: NSARCHIVE_BAY_OF_PIGS_3,
    officialUrl: NSARCHIVE_BAY_OF_PIGS_3,
    dataUrl: bayOfPigsPdf('19610417.pdf'),
    citation: 'Handwritten Order from Commander-in-Chief Fidel Castro to Captain Jose R. Fernandez, April 17, 1961, Spanish original.',
    summary: 'Spanish original of Castro battlefield orders during the Bay of Pigs invasion.',
  },
  {
    ...bayOfPigsDefaults,
    id: 'nsarchive-bop-19610418a-castro-message-translation',
    title: 'Handwritten message from Fidel Castro to Julio (Flavio Bravo Pardo), translation',
    date: '1961-04-18',
    documentNumber: '19610418a-trans',
    url: NSARCHIVE_BAY_OF_PIGS_3,
    officialUrl: NSARCHIVE_BAY_OF_PIGS_3,
    dataUrl: bayOfPigsPdf('19610418a-trans.pdf'),
    citation: 'Handwritten Message from Commander-in-Chief Fidel Castro to Julio (Flavio Bravo Pardo), April 18, 1961, English translation.',
    summary: 'Translated Castro handwritten message from the second day of the Bay of Pigs fighting.',
  },
  {
    ...bayOfPigsDefaults,
    id: 'nsarchive-bop-19610418a-castro-message-original',
    title: 'Handwritten message from Fidel Castro to Julio (Flavio Bravo Pardo), Spanish original',
    date: '1961-04-18',
    documentNumber: '19610418a',
    url: NSARCHIVE_BAY_OF_PIGS_3,
    officialUrl: NSARCHIVE_BAY_OF_PIGS_3,
    dataUrl: bayOfPigsPdf('19610418a.pdf'),
    citation: 'Handwritten Message from Commander-in-Chief Fidel Castro to Julio (Flavio Bravo Pardo), April 18, 1961, Spanish original and transcription.',
    summary: 'Spanish original and transcription of Castro message during the Bay of Pigs battle.',
  },
  {
    ...bayOfPigsDefaults,
    id: 'nsarchive-bop-19610418b-castro-order-translation',
    title: 'Handwritten order from Fidel Castro to Captain Jose R. Fernandez (April 18 translation)',
    date: '1961-04-18',
    documentNumber: '19610418b-trans',
    url: NSARCHIVE_BAY_OF_PIGS_3,
    officialUrl: NSARCHIVE_BAY_OF_PIGS_3,
    dataUrl: bayOfPigsPdf('19610418b-trans.pdf'),
    citation: 'Handwritten Order from Commander-in-Chief Fidel Castro to Captain Jose R. Fernandez, April 18, 1961, English translation.',
    summary: 'Translated Castro order issued during the second day of the Bay of Pigs battle.',
  },
  {
    ...bayOfPigsDefaults,
    id: 'nsarchive-bop-19610418b-castro-order-original',
    title: 'Handwritten order from Fidel Castro to Captain Jose R. Fernandez (April 18 Spanish original)',
    date: '1961-04-18',
    documentNumber: '19610418b',
    url: NSARCHIVE_BAY_OF_PIGS_3,
    officialUrl: NSARCHIVE_BAY_OF_PIGS_3,
    dataUrl: bayOfPigsPdf('19610418b.pdf'),
    citation: 'Handwritten Order from Commander-in-Chief Fidel Castro to Captain Jose R. Fernandez, April 18, 1961, Spanish original.',
    summary: 'Spanish original of Castro order issued during the second day of the Bay of Pigs battle.',
  },
  {
    ...bayOfPigsDefaults,
    id: 'nsarchive-bop-19610419-castro-order-translation',
    title: 'Handwritten order from Fidel Castro to Captain Roger Garcia (translation)',
    date: '1961-04-19',
    documentNumber: '19610419-trans',
    url: NSARCHIVE_BAY_OF_PIGS_3,
    officialUrl: NSARCHIVE_BAY_OF_PIGS_3,
    dataUrl: bayOfPigsPdf('19610419-trans.pdf'),
    citation: 'Handwritten Order from Commander-in-Chief Fidel Castro to Captain Roger Garcia, April 19, 1961, English translation.',
    summary: 'Translated Castro order from the final phase of the Bay of Pigs battle.',
  },
  {
    ...bayOfPigsDefaults,
    id: 'nsarchive-bop-19610419-castro-order-original',
    title: 'Handwritten order from Fidel Castro to Captain Roger Garcia (Spanish original)',
    date: '1961-04-19',
    documentNumber: '19610419',
    url: NSARCHIVE_BAY_OF_PIGS_3,
    officialUrl: NSARCHIVE_BAY_OF_PIGS_3,
    dataUrl: bayOfPigsPdf('19610419.pdf'),
    citation: 'Handwritten Order from Commander-in-Chief Fidel Castro to Captain Roger Garcia, April 19, 1961, Spanish original.',
    summary: 'Spanish original of Castro order from the final phase of the Bay of Pigs battle.',
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-20293-goodpaster-football',
    title: 'Memorandum for the Record by Brigadier General Andrew J. Goodpaster, 25 January 1961, Top Secret',
    date: '1961-01-25',
    documentNumber: 'Document 08',
    container: 'Presidential Control of Nuclear Weapons: The Football',
    section: 'Nuclear command and continuity',
    url: nsarchiveDocument('/document/20293-national-security-archive-doc-08-memorandum'),
    officialUrl: nsarchiveDocument('/document/20293-national-security-archive-doc-08-memorandum'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/6895256/National-Security-Archive-Doc-08-Memorandum-for.pdf'),
    citation: 'Memorandum for the Record by Brig. Gen. Andrew J. Goodpaster, January 25, 1961, Top Secret.',
    summary: 'Goodpaster recorded the presidential transition briefing on emergency action documents and the satchel later known as the nuclear football.',
    topics: ['Nuclear', 'Defense'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-15873-vienna-iaea',
    title: 'U.S. Embassy Vienna telegram 1194 to State Department, 26 January 1961, Official Use Only',
    date: '1961-01-26',
    documentNumber: 'Document 37A',
    container: 'IAEA safeguards and nuclear policy documents',
    section: 'IAEA safeguards',
    url: nsarchiveDocument('/document/15873-document-37a-u-s-embassy-vienna-telegram-1194'),
    officialUrl: nsarchiveDocument('/document/15873-document-37a-u-s-embassy-vienna-telegram-1194'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/4116387/Document-37A-U-S-Embassy-Vienna-telegram-1194-to.pdf'),
    citation: 'U.S. Embassy Vienna telegram 1194 to Department of State, January 26, 1961.',
    summary: 'Telegram reporting Board of Governors debate over the International Atomic Energy Agency safeguards document.',
    sourceNote: 'Source: RG 59 Central Decimal Files, 1960-1963, 398.1901-IAEA/1-2661.',
    topics: ['Nuclear', 'Diplomacy'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-21605-rusk-reid-israel',
    title: 'Secretary of State Rusk to President Kennedy, "Your Appointment with Ogden R. Reid, Recently Ambassador to Israel," with memorandum and chronology attached, Secret, Excised copy',
    date: '1961-01-30',
    documentNumber: 'Document 1A',
    container: 'Concerned About Nuclear Weapons Potential, John F. Kennedy Pushed for Inspection of Israel Nuclear Facilities',
    section: 'Israel and Dimona',
    url: nsarchiveDocument('/document/21605-document-1a-secretary-state-rusk-president'),
    officialUrl: nsarchiveDocument('/document/21605-document-1a-secretary-state-rusk-president'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/2806668/Document-1A-Secretary-of-State-Rusk-to-President.pdf'),
    citation: 'Secretary of State Rusk to President Kennedy, January 30, 1961, Secret, excised copy.',
    summary: 'Rusk prepared Kennedy for a briefing with former Ambassador Ogden Reid on U.S.-Israel relations and the Dimona reactor.',
    topics: ['Middle East', 'Nuclear', 'Diplomacy'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-21606-reid-conversation',
    title: 'Memorandum of Conversation, "Ambassador Reid\'s Review of His Conversation with President Kennedy," Secret',
    date: '1961-01-31',
    documentNumber: 'Document 1B',
    container: 'Concerned About Nuclear Weapons Potential, John F. Kennedy Pushed for Inspection of Israel Nuclear Facilities',
    section: 'Israel and Dimona',
    url: nsarchiveDocument('/document/21606-document-1b-memorandum-conversation'),
    officialUrl: nsarchiveDocument('/document/21606-document-1b-memorandum-conversation'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/2806669/Document-1B-Memorandum-of-Conversation.pdf'),
    citation: 'Memorandum of Conversation, Ambassador Reid\'s Review of His Conversation with President Kennedy, January 31, 1961.',
    summary: 'Memorandum recording Ambassador Reid\'s report on his conversation with Kennedy about Israel and Dimona.',
    topics: ['Middle East', 'Nuclear', 'Diplomacy'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-17336-thompson-soviet-cable',
    title: 'Telegram From the Embassy in the Soviet Union to the Department of State',
    date: '1961-02-01',
    documentNumber: 'Document 04',
    container: 'Tommy Thompson - The Kremlinologist',
    section: 'Soviet policy',
    url: nsarchiveDocument('/document/17336-document-04-telegram-embassy'),
    officialUrl: nsarchiveDocument('/document/17336-document-04-telegram-embassy'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/5188887/Document-04-Telegram-From-the-Embassy-in-the.pdf'),
    citation: 'Telegram from the Embassy in the Soviet Union to the Department of State, February 1, 1961.',
    summary: 'Ambassador Llewellyn Thompson assessed Soviet leadership, negotiating posture, and possible U.S. policy approaches for the new administration.',
    sourceNote: 'Source: Foreign Relations of the United States, 1961-1963, Volume V, Soviet Union, Document 20.',
    topics: ['USSR', 'Diplomacy'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-21607-israeli-reactor-suggestion',
    title: 'Assistant Secretary of State for Near Eastern Affairs to Secretary of State, "President\'s Suggestion re Israeli Reactor," Secret',
    date: '1961-02-02',
    documentNumber: 'Document 2A',
    container: 'Concerned About Nuclear Weapons Potential, John F. Kennedy Pushed for Inspection of Israel Nuclear Facilities',
    section: 'Israel and Dimona',
    url: nsarchiveDocument('/document/21607-document-2a-assistant-secretary-state'),
    officialUrl: nsarchiveDocument('/document/21607-document-2a-assistant-secretary-state'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/2806670/Document-2A-Assistant-Secretary-of-State-for.pdf'),
    citation: 'Assistant Secretary of State for Near Eastern Affairs to Secretary of State, President\'s Suggestion re Israeli Reactor, February 2, 1961.',
    summary: 'State Department memorandum following Kennedy\'s suggestion that the United States arrange a visit to Israel\'s Dimona reactor.',
    topics: ['Middle East', 'Nuclear', 'Diplomacy'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-21608-israeli-reactor-memcon',
    title: 'Memorandum of Conversation, "Israeli Reactor," Confidential',
    date: '1961-02-03',
    documentNumber: 'Document 2B',
    container: 'Concerned About Nuclear Weapons Potential, John F. Kennedy Pushed for Inspection of Israel Nuclear Facilities',
    section: 'Israel and Dimona',
    url: nsarchiveDocument('/document/21608-document-2b-memorandum-conversation-israeli'),
    officialUrl: nsarchiveDocument('/document/21608-document-2b-memorandum-conversation-israeli'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/2806671/Document-2B-Memorandum-of-Conversation-Israeli.pdf'),
    citation: 'Memorandum of Conversation, Israeli Reactor, February 3, 1961.',
    summary: 'Memorandum of conversation on Israeli nuclear issues and U.S. interest in inspecting the Dimona reactor.',
    topics: ['Middle East', 'Nuclear', 'Diplomacy'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-21609-rusk-israeli-reactor',
    title: 'Memorandum, Secretary of State Rusk for the President, "Israeli Reactor," Secret',
    date: '1961-02-08',
    documentNumber: 'Document 2C',
    container: 'Concerned About Nuclear Weapons Potential, John F. Kennedy Pushed for Inspection of Israel Nuclear Facilities',
    section: 'Israel and Dimona',
    url: nsarchiveDocument('/document/21609-document-2c-memorandum-secretary-state-rusk'),
    officialUrl: nsarchiveDocument('/document/21609-document-2c-memorandum-secretary-state-rusk'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/2806672/Document-2C-Memorandum-Secretary-of-State-Rusk.pdf'),
    citation: 'Secretary of State Rusk for the President, Israeli Reactor, February 8, 1961.',
    summary: 'Rusk reported to Kennedy on the Israeli reactor question and State Department efforts to arrange inspection access.',
    topics: ['Middle East', 'Nuclear', 'Diplomacy'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-21610-israel-reactor-inspection',
    title: 'Memorandum of Conversation, "Inspection of Israel\'s New Atomic Reactor," Secret',
    date: '1961-02-13',
    documentNumber: 'Document 2D',
    container: 'Concerned About Nuclear Weapons Potential, John F. Kennedy Pushed for Inspection of Israel Nuclear Facilities',
    section: 'Israel and Dimona',
    url: nsarchiveDocument('/document/21610-document-2d-memorandum-conversation'),
    officialUrl: nsarchiveDocument('/document/21610-document-2d-memorandum-conversation'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/2806673/Document-2D-Memorandum-of-Conversation.pdf'),
    citation: 'Memorandum of Conversation, Inspection of Israel\'s New Atomic Reactor, February 13, 1961.',
    summary: 'U.S.-Israeli conversation on arranging an inspection visit to the Dimona reactor.',
    topics: ['Middle East', 'Nuclear', 'Diplomacy'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-17338-thinking-soviet-leadership',
    title: 'The Thinking Of The Soviet Leadership, Cabinet Room, February 11, 1961. Notes on Discussion. Drafted by McGeorge Bundy',
    date: '1961-02-13',
    documentNumber: 'Document 05',
    container: 'Tommy Thompson - The Kremlinologist',
    section: 'Soviet policy',
    url: nsarchiveDocument('/document/17338-document-05-thinking-soviet'),
    officialUrl: nsarchiveDocument('/document/17338-document-05-thinking-soviet'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/5188888/Document-05-The-Thinking-Of-The-Soviet.pdf'),
    citation: 'The Thinking of the Soviet Leadership, notes on Cabinet Room discussion, February 11, 1961, drafted by McGeorge Bundy.',
    summary: 'Notes of a Kennedy meeting with Soviet experts, including Thompson\'s recommendations on U.S. policy toward the Soviet Union.',
    sourceNote: 'Source: Foreign Relations of the United States, 1961-1963, Volume V, Soviet Union, Document 26.',
    topics: ['USSR', 'Berlin', 'Diplomacy'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-28543-holifield-report',
    title: 'Representative Chet Holifield to President Kennedy, enclosing Report on Inspection Trip to NATO Countries, Top Secret, Excised copy',
    date: '1961-02-15',
    documentNumber: 'Document 5',
    container: 'The U.S. Nuclear Presence in Western Europe, 1954-1962, Part II',
    section: 'NATO nuclear custody',
    url: nsarchiveDocument('/document/28543-document-5-representative-chet-holifield-chairman-ad-hoc-subcommittee-president'),
    officialUrl: nsarchiveDocument('/document/28543-document-5-representative-chet-holifield-chairman-ad-hoc-subcommittee-president'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/rdua0b-aismv/05.pdf'),
    citation: 'Representative Chet Holifield to President Kennedy, February 15, 1961, with report on NATO nuclear weapons sites.',
    summary: 'Holifield sent Kennedy a report raising concerns over custody, control, security, and political stability around U.S. nuclear weapons in NATO countries.',
    sourceNote: 'Source: Digital National Security Archive.',
    topics: ['NATO', 'Nuclear', 'Defense', 'Europe'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-28544-holifield-letter',
    title: 'Representative Chet Holifield to President Kennedy, 15 February 1961, no classification markings',
    date: '1961-02-15',
    documentNumber: 'Document 6',
    container: 'The U.S. Nuclear Presence in Western Europe, 1954-1962, Part II',
    section: 'NATO nuclear custody',
    url: nsarchiveDocument('/document/28544-document-6-representative-chet-holifield-chairman-ad-hoc-subcommittee-president'),
    officialUrl: nsarchiveDocument('/document/28544-document-6-representative-chet-holifield-chairman-ad-hoc-subcommittee-president'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/rdua0b-aismv/06.pdf'),
    citation: 'Representative Chet Holifield to President Kennedy, February 15, 1961.',
    summary: 'Full version of Holifield\'s letter to Kennedy, including references to Jupiter missile deployments in Italy and Turkey.',
    sourceNote: 'Source: Digital National Security Archive.',
    topics: ['NATO', 'Nuclear', 'Defense', 'Europe'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-19684-millar-turkey',
    title: 'John Y. Millar to William N. Dale, Counselor, U.S. Embassy Turkey, 15 February 1961, Secret',
    date: '1961-02-15',
    documentNumber: 'Document 11',
    container: 'NATO atomic stockpile and MRBM documents',
    section: 'Turkey and nuclear deployments',
    url: nsarchiveDocument('/document/19684-national-security-archive-doc-11-john-y-millar'),
    officialUrl: nsarchiveDocument('/document/19684-national-security-archive-doc-11-john-y-millar'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/6532125/National-Security-Archive-Doc-11-John-Y-Millar.pdf'),
    citation: 'John Y. Millar to William N. Dale, U.S. Embassy Turkey, February 15, 1961.',
    summary: 'Memorandum on nuclear data transfer and possible Turkish nuclear-capable force arrangements within NATO.',
    sourceNote: 'Source: RG 59, Bureau of European Affairs, Office of European Regional Affairs.',
    topics: ['NATO', 'Nuclear', 'Defense', 'Middle East'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-21611-israel-security-problems',
    title: 'Memorandum of Conversation, "Israel\'s Security and Other Problems," Secret',
    date: '1961-02-16',
    documentNumber: 'Document 2E',
    container: 'Concerned About Nuclear Weapons Potential, John F. Kennedy Pushed for Inspection of Israel Nuclear Facilities',
    section: 'Israel and Dimona',
    url: nsarchiveDocument('/document/21611-document-2e-memorandum-conversation-israel-s'),
    officialUrl: nsarchiveDocument('/document/21611-document-2e-memorandum-conversation-israel-s'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/2806674/Document-2E-Memorandum-of-Conversation-Israel-s.pdf'),
    citation: 'Memorandum of Conversation, Israel\'s Security and Other Problems, February 16, 1961.',
    summary: 'U.S.-Israeli conversation on security problems, Dimona, and regional implications of the Israeli reactor.',
    topics: ['Middle East', 'Nuclear', 'Diplomacy', 'USSR'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-19442-bombay-india-nuclear',
    title: 'U.S. Consul General Bombay Despatch 484 to Department of State, "Possible Indian Desire for Nuclear Weapons Development," Confidential',
    date: '1961-02-20',
    documentNumber: 'Document 05',
    container: 'Nuclear nonproliferation documents',
    section: 'India nuclear policy',
    url: nsarchiveDocument('/document/19442-national-security-archive-doc-05-u-s-consul'),
    officialUrl: nsarchiveDocument('/document/19442-national-security-archive-doc-05-u-s-consul'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/6199561/National-Security-Archive-Doc-05-U-S-Consul.pdf'),
    citation: 'U.S. Consul General Bombay Despatch 484 to Department of State, February 20, 1961.',
    summary: 'Consular reporting on Indian nuclear views and the possibility of nuclear weapons development.',
    topics: ['Nuclear', 'Asia', 'Diplomacy'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-21612-reid-un-telegram',
    title: 'U.S. Mission to the United Nations telegram 2242 to Department of State, "Eyes Only" from Reid to Secretary, Secret',
    date: '1961-02-20',
    documentNumber: 'Document 3A',
    container: 'Concerned About Nuclear Weapons Potential, John F. Kennedy Pushed for Inspection of Israel Nuclear Facilities',
    section: 'Israel and Dimona',
    url: nsarchiveDocument('/document/21612-document-3a-u-s-mission-united-nations'),
    officialUrl: nsarchiveDocument('/document/21612-document-3a-u-s-mission-united-nations'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/2806675/Document-3A-U-S-Mission-to-the-United-Nations.pdf'),
    citation: 'U.S. Mission to the United Nations telegram 2242 to Department of State, February 20, 1961.',
    summary: 'Telegram reporting discussions on arranging a U.S. visit to the Dimona reactor and Israeli political timing.',
    topics: ['Middle East', 'Nuclear', 'Diplomacy', 'United Nations'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-27403-cuba-embargo-questions',
    title: 'NSC memorandum, "Memorandum for the Secretary of State," February 21, 1961',
    date: '1961-02-21',
    documentNumber: 'Document 4',
    container: 'Cuba Embargoed: U.S. Trade Sanctions Turn Sixty',
    section: 'Cuba embargo policy',
    url: nsarchiveDocument('/document/27403-document-4-nsc-memorandum-memorandum-secretary-state-february-21-1961'),
    officialUrl: nsarchiveDocument('/document/27403-document-4-nsc-memorandum-memorandum-secretary-state-february-21-1961'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/Embargo4JFKquestions.pdf'),
    citation: 'NSC Memorandum for the Secretary of State, February 21, 1961.',
    summary: 'Kennedy, through McGeorge Bundy, asked Rusk whether expanding the Cuba embargo would save exchange, hurt Castro, and serve the public interest.',
    topics: ['Cuba', 'Latin America', 'Diplomacy'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-28546-fowler-jcs-debrief',
    title: 'R.D. Fowler memorandum for the record, "Debrief of President\'s Meeting with JCS on 23 Feb 1961," Top Secret',
    date: '1961-02-24',
    documentNumber: 'Document 8',
    container: 'The U.S. Nuclear Presence in Western Europe, 1954-1962, Part II',
    section: 'Nuclear command and NATO',
    url: nsarchiveDocument('/document/28546-document-8-rd-fowler-office-chief-naval-operations-memorandum-record-debrief-presi'),
    officialUrl: nsarchiveDocument('/document/28546-document-8-rd-fowler-office-chief-naval-operations-memorandum-record-debrief-presi'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/rdua0b-aismv/08.pdf'),
    citation: 'R.D. Fowler, Memorandum for the Record, Debrief of President\'s Meeting with JCS on February 23, 1961.',
    summary: 'Fowler recorded Kennedy\'s questions to the Joint Chiefs about nuclear weapons control, presidential authority, and the Holifield report.',
    sourceNote: 'Source: U.S. Navy Heritage and History Command, Archives, Double-Zero Files 1966.',
    topics: ['NATO', 'Nuclear', 'Defense'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-27404-cuba-embargo-rusk',
    title: 'State Department memorandum, "Questions Arising from Senator Smathers Recommendation that Remaining Exports from Cuba to the United States by Embargoed," Secret',
    date: '1961-02-24',
    documentNumber: 'Document 5',
    container: 'Cuba Embargoed: U.S. Trade Sanctions Turn Sixty',
    section: 'Cuba embargo policy',
    url: nsarchiveDocument('/document/27404-document-5-state-department-memorandum-questions-arising-senator-smathers'),
    officialUrl: nsarchiveDocument('/document/27404-document-5-state-department-memorandum-questions-arising-senator-smathers'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/Embargo5Ruskresponse61.pdf'),
    citation: 'State Department memorandum on Senator Smathers recommendation concerning Cuba exports, February 24, 1961.',
    summary: 'Rusk answered Kennedy\'s questions on the merits and public-interest case for a fuller trade embargo against Cuba.',
    topics: ['Cuba', 'Latin America', 'Diplomacy'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-21613-us-israel-dimona',
    title: 'Memorandum of Conversation, "U.S.-Israeli Relations - The Dimona Reactor," Confidential',
    date: '1961-02-26',
    documentNumber: 'Document 3B',
    container: 'Concerned About Nuclear Weapons Potential, John F. Kennedy Pushed for Inspection of Israel Nuclear Facilities',
    section: 'Israel and Dimona',
    url: nsarchiveDocument('/document/21613-document-3b-memorandum-conversation-u-s'),
    officialUrl: nsarchiveDocument('/document/21613-document-3b-memorandum-conversation-u-s'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/2806676/Document-3B-Memorandum-of-Conversation-U-S.pdf'),
    citation: 'Memorandum of Conversation, U.S.-Israeli Relations - The Dimona Reactor, February 26, 1961.',
    summary: 'Memorandum of conversation on U.S.-Israeli relations and the unresolved question of access to Dimona.',
    topics: ['Middle East', 'Nuclear', 'Diplomacy'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-28542-pender-stockpile-custody',
    title: 'J.H. Pender, "State Department Role in Atomic Weapons Stockpile Custodial Arrangements," Secret',
    date: '1961-02-28',
    documentNumber: 'Document 4',
    container: 'The U.S. Nuclear Presence in Western Europe, 1954-1962, Part II',
    section: 'NATO nuclear custody',
    url: nsarchiveDocument('/document/28542-document-4-jh-pender-lsfp-assistant-legal-adviser-special-functional-problems-state'),
    officialUrl: nsarchiveDocument('/document/28542-document-4-jh-pender-lsfp-assistant-legal-adviser-special-functional-problems-state'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/rdua0b-aismv/04.pdf'),
    citation: 'J.H. Pender, State Department Role in Atomic Weapons Stockpile Custodial Arrangements, February 28, 1961.',
    summary: 'State Department legal memorandum on U.S. knowledge and responsibility for custody arrangements at nuclear weapons sites in Europe.',
    sourceNote: 'Source: Digital National Security Archive.',
    topics: ['NATO', 'Nuclear', 'Defense', 'Europe'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-28549-kohler-atomic-stockpile',
    title: 'Foy D. Kohler to the Secretary, "Executive Branch Position on Further Negotiation of Pending Atomic Cooperation and Atomic Stockpile Agreements," Secret',
    date: '1961-02-28',
    documentNumber: 'Document 11',
    container: 'The U.S. Nuclear Presence in Western Europe, 1954-1962, Part II',
    section: 'NATO atomic stockpile',
    url: nsarchiveDocument('/document/28549-document-11-eur-foy-d-kohler-secretary-executive-branch-position-further-negotiation'),
    officialUrl: nsarchiveDocument('/document/28549-document-11-eur-foy-d-kohler-secretary-executive-branch-position-further-negotiation'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/rdua0b-aismv/11.pdf'),
    citation: 'Foy D. Kohler to the Secretary, February 28, 1961, on atomic cooperation and stockpile agreements.',
    summary: 'Kohler briefed Rusk on negotiations involving NATO atomic information and stockpile arrangements with European allies.',
    sourceNote: 'Source: RG 59, Central Decimal Files, 611.657.',
    topics: ['NATO', 'Nuclear', 'Defense', 'Europe'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-21614-rusk-israeli-reactor',
    title: 'Memorandum by Secretary Rusk to President Kennedy, "Israeli Reactor," with memo from Jones to Rusk attached, Confidential',
    date: '1961-03-03',
    documentNumber: 'Document 3C',
    container: 'Concerned About Nuclear Weapons Potential, John F. Kennedy Pushed for Inspection of Israel Nuclear Facilities',
    section: 'Israel and Dimona',
    url: nsarchiveDocument('/document/21614-document-3c-memorandum-secretary-rusk'),
    officialUrl: nsarchiveDocument('/document/21614-document-3c-memorandum-secretary-rusk'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/2806677/Document-3C-Memorandum-by-Secretary-Rusk-to.pdf'),
    citation: 'Secretary Rusk to President Kennedy, Israeli Reactor, March 3, 1961.',
    summary: 'Rusk updated Kennedy on Israeli reactor inspection discussions and attached a Jones memorandum on the same issue.',
    topics: ['Middle East', 'Nuclear', 'Diplomacy'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-21615-dimona-memcon',
    title: 'Memorandum of Conversation, "Dimona Reactor," Secret',
    date: '1961-03-13',
    documentNumber: 'Document 3D',
    container: 'Concerned About Nuclear Weapons Potential, John F. Kennedy Pushed for Inspection of Israel Nuclear Facilities',
    section: 'Israel and Dimona',
    url: nsarchiveDocument('/document/21615-document-3d-memorandum-conversation-dimona'),
    officialUrl: nsarchiveDocument('/document/21615-document-3d-memorandum-conversation-dimona'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/2806678/Document-3D-Memorandum-of-Conversation-Dimona.pdf'),
    citation: 'Memorandum of Conversation, Dimona Reactor, March 13, 1961.',
    summary: 'Memorandum of conversation continuing U.S.-Israeli exchanges over access to the Dimona reactor.',
    topics: ['Middle East', 'Nuclear', 'Diplomacy'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-23731-norstad-volkel',
    title: 'Memorandum for the Record by Major H.F. Williams, "General Norstad\'s Visit to [Volkel Air Force Base] on 29 March 1961," Secret',
    date: '1961-03-19',
    documentNumber: 'Document 09',
    container: 'The U.S. Nuclear Presence in Western Europe, 1954-1962, Part II',
    section: 'NATO nuclear storage',
    url: nsarchiveDocument('/document/23731-memorandum-record-major-h-f-williams-executive-assistant-saceur-general-norstad-s'),
    officialUrl: nsarchiveDocument('/document/23731-memorandum-record-major-h-f-williams-executive-assistant-saceur-general-norstad-s'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/qvvm8h-lx1ik/09.pdf'),
    citation: 'Major H.F. Williams, Memorandum for the Record on General Norstad\'s visit to Volkel Air Force Base, March 1961.',
    summary: 'Report on SACEUR General Norstad\'s briefing at a nuclear storage site in the Netherlands under NATO atomic stockpile arrangements.',
    sourceNote: 'Source: Dwight D. Eisenhower Library, Lauris Norstad Papers.',
    topics: ['NATO', 'Nuclear', 'Defense', 'Europe'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-28362-cia-elint-3025',
    title: 'Office of Scientific Intelligence, CIA, ELINT Report of Mission 3025, March 27, 1961, Top Secret',
    date: '1961-03-27',
    documentNumber: 'Document 4',
    container: 'CIA signals intelligence and reconnaissance documents',
    section: 'Laos, Vietnam, and electronic intelligence',
    url: nsarchiveDocument('/document/28362-document-4-office-scientific-intelligence-cia-elint-report-mission-3025-march-27'),
    officialUrl: nsarchiveDocument('/document/28362-document-4-office-scientific-intelligence-cia-elint-report-mission-3025-march-27'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/rd5srg-2je8j/ciasignals_04.pdf'),
    citation: 'Office of Scientific Intelligence, CIA, ELINT Report of Mission 3025, March 27, 1961.',
    summary: 'CIA report on U-2 electronic intelligence collection over the South China Sea, Laos, South Vietnam, and North Vietnam.',
    sourceNote: 'Source: CREST, NARA, College Park.',
    topics: ['Laos', 'Vietnam', 'Asia', 'Intelligence', 'Defense'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-21616-dimona-memcon',
    title: 'Memorandum of Conversation, "Dimona Reactor," Secret',
    date: '1961-03-28',
    documentNumber: 'Document 3E',
    container: 'Concerned About Nuclear Weapons Potential, John F. Kennedy Pushed for Inspection of Israel Nuclear Facilities',
    section: 'Israel and Dimona',
    url: nsarchiveDocument('/document/21616-document-3e-memorandum-conversation-dimona'),
    officialUrl: nsarchiveDocument('/document/21616-document-3e-memorandum-conversation-dimona'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/2806679/Document-3E-Memorandum-of-Conversation-Dimona.pdf'),
    citation: 'Memorandum of Conversation, Dimona Reactor, March 28, 1961.',
    summary: 'Memorandum of conversation as U.S. officials pressed for an inspection visit to the Dimona reactor.',
    topics: ['Middle East', 'Nuclear', 'Diplomacy'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-21617-rusk-dimona-history',
    title: 'Memorandum from Secretary Rusk to President Kennedy, "Dimona Reactor in Israel," with history attached, Secret',
    date: '1961-03-30',
    documentNumber: 'Document 3F',
    container: 'Concerned About Nuclear Weapons Potential, John F. Kennedy Pushed for Inspection of Israel Nuclear Facilities',
    section: 'Israel and Dimona',
    url: nsarchiveDocument('/document/21617-document-3f-memorandum-secretary-rusk'),
    officialUrl: nsarchiveDocument('/document/21617-document-3f-memorandum-secretary-rusk'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/2806680/Document-3F-Memorandum-from-Secretary-Rusk-to.pdf'),
    citation: 'Secretary Rusk to President Kennedy, Dimona Reactor in Israel, March 30, 1961.',
    summary: 'Rusk sent Kennedy an update and background history on U.S. interest in Israel\'s atomic energy activities.',
    topics: ['Middle East', 'Nuclear', 'Diplomacy'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-15876-iaea-safeguards',
    title: 'International Atomic Energy Agency, "The Agency\'s Safeguards," INFCIRC/26',
    date: '1961-03-30',
    documentNumber: 'Document 37D',
    container: 'IAEA safeguards and nuclear policy documents',
    section: 'IAEA safeguards',
    url: nsarchiveDocument('/document/15876-document-37d-international-atomic-energy-agency'),
    officialUrl: nsarchiveDocument('/document/15876-document-37d-international-atomic-energy-agency'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/4116390/Document-37D-International-Atomic-Energy-Agency.pdf'),
    citation: 'International Atomic Energy Agency, The Agency\'s Safeguards, INFCIRC/26, March 30, 1961.',
    summary: 'IAEA safeguards document setting out early international nuclear safeguards policy.',
    sourceNote: 'Source: International Atomic Energy Agency.',
    topics: ['Nuclear', 'Diplomacy'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-21618-us-visit-dimona',
    title: 'Memorandum of Conversation, "U.S. Visit to Dimona Reactor Site," Secret',
    date: '1961-04-10',
    documentNumber: 'Document 4A',
    container: 'Concerned About Nuclear Weapons Potential, John F. Kennedy Pushed for Inspection of Israel Nuclear Facilities',
    section: 'Israel and Dimona',
    url: nsarchiveDocument('/document/21618-document-4a-memorandum-conversation-u-s-visit'),
    officialUrl: nsarchiveDocument('/document/21618-document-4a-memorandum-conversation-u-s-visit'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/2806681/Document-4A-Memorandum-of-Conversation-U-S-Visit.pdf'),
    citation: 'Memorandum of Conversation, U.S. Visit to Dimona Reactor Site, April 10, 1961.',
    summary: 'Memorandum on Israeli agreement and conditions for a quiet U.S. visit to the Dimona reactor site.',
    topics: ['Middle East', 'Nuclear', 'Diplomacy'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-21619-harman-appointment',
    title: 'Memorandum by Assistant Secretary Jones to Secretary of State Rusk, "Your Appointment with Israeli Ambassador Harman," Secret',
    date: '1961-04-11',
    documentNumber: 'Document 4B',
    container: 'Concerned About Nuclear Weapons Potential, John F. Kennedy Pushed for Inspection of Israel Nuclear Facilities',
    section: 'Israel and Dimona',
    url: nsarchiveDocument('/document/21619-document-4b-memorandum-assistant-secretary'),
    officialUrl: nsarchiveDocument('/document/21619-document-4b-memorandum-assistant-secretary'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/2806682/Document-4B-Memorandum-by-Assistant-Secretary.pdf'),
    citation: 'Assistant Secretary Jones to Secretary Rusk, Your Appointment with Israeli Ambassador Harman, April 11, 1961.',
    summary: 'Jones briefed Rusk before meeting Ambassador Harman, as Ben-Gurion sought a Kennedy meeting while U.S. officials insisted on a Dimona visit.',
    topics: ['Middle East', 'Nuclear', 'Diplomacy'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-20816-khrushchev-vostok',
    title: 'Nikita S. Khrushchev, "Proposals in connection with the launch of the Vostok spacecraft with Yuri Gagarin," April 11, 1961',
    date: '1961-04-11',
    documentNumber: 'Document 1',
    container: 'U.S.-Soviet Cooperation in Outer Space, Part 1',
    section: 'Space policy and Soviet-U.S. relations',
    url: nsarchiveDocument('/document/20816-01'),
    officialUrl: nsarchiveDocument('/document/20816-01'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/20604732/01.pdf'),
    citation: 'Nikita S. Khrushchev, Proposals in connection with the launch of Vostok with Yuri Gagarin, April 11, 1961.',
    summary: 'Translated Soviet document prepared around Gagarin\'s flight, providing context for Kennedy\'s space-cooperation message to Khrushchev.',
    sourceNote: 'Source: Russian State Archive of Contemporary History.',
    topics: ['USSR', 'Nuclear', 'Diplomacy'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-20832-kennedy-khrushchev-space',
    title: 'White House Press Secretary Telegram, John F. Kennedy to Nikita S. Khrushchev, April 12, 1961',
    date: '1961-04-12',
    documentNumber: 'Document 2',
    container: 'U.S.-Soviet Cooperation in Outer Space, Part 1',
    section: 'Space policy and Soviet-U.S. relations',
    url: nsarchiveDocument('/document/20832-02'),
    officialUrl: nsarchiveDocument('/document/20832-02'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/20606509/02.pdf'),
    citation: 'White House Press Secretary Telegram, John F. Kennedy to Nikita S. Khrushchev, April 12, 1961.',
    summary: 'Kennedy congratulated Khrushchev on Gagarin\'s flight and expressed interest in U.S.-Soviet cooperation in outer space.',
    sourceNote: 'Source: John F. Kennedy Presidential Library.',
    topics: ['USSR', 'Diplomacy'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-21620-us-visit-dimona',
    title: 'Memorandum of Conversation, "U.S. Visit to Dimona," Secret',
    date: '1961-04-17',
    documentNumber: 'Document 5A',
    container: 'Concerned About Nuclear Weapons Potential, John F. Kennedy Pushed for Inspection of Israel Nuclear Facilities',
    section: 'Israel and Dimona',
    url: nsarchiveDocument('/document/21620-document-5a-memorandum-conversation-u-s-visit'),
    officialUrl: nsarchiveDocument('/document/21620-document-5a-memorandum-conversation-u-s-visit'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/2806683/Document-5A-Memorandum-of-Conversation-U-S-Visit.pdf'),
    citation: 'Memorandum of Conversation, U.S. Visit to Dimona, April 17, 1961.',
    summary: 'Memorandum on secrecy, timing, and conditions for the U.S. visit to Dimona before Kennedy met Ben-Gurion.',
    topics: ['Middle East', 'Nuclear', 'Diplomacy'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-29393-kozlov-suslov-bravo',
    title: 'Memorandum of Conversation between Frol Kozlov, Mikhail Suslov and Flavio Bravo, Moscow',
    date: '1961-03-03',
    documentNumber: 'Document 3',
    container: 'The Cuban Missile Crisis @ 60: Getting to Know the Cubans, Part Two',
    section: 'Cuba and Soviet relations',
    url: nsarchiveDocument('/document/29393-document-3-memorandum-conversation-between-frol-kozlov-mikhail-suslov-and-flavio'),
    officialUrl: nsarchiveDocument('/document/29393-document-3-memorandum-conversation-between-frol-kozlov-mikhail-suslov-and-flavio'),
    dataUrl: nsarchiveDocument('/sites/default/files/2022-11/1961-03-03-Bravo-Flavio-Kozlov-memcon.pdf'),
    citation: 'Memorandum of Conversation between Frol Kozlov, Mikhail Suslov and Flavio Bravo, Moscow, March 3, 1961.',
    summary: 'Cuban communist leader Flavio Bravo briefed Soviet officials on the Cuban political and military situation before the Bay of Pigs invasion.',
    sourceNote: 'Source: Archive of the President of the Russian Federation; translation by Adam Mayle and Svetlana Savranskaya.',
    topics: ['Cuba', 'Latin America', 'USSR', 'Diplomacy', 'Bay of Pigs'],
  },
];
