const ISCAP_2014_030_URL = 'https://www.archives.gov/declassification/iscap/pdf/2014-030';
const CIA_READING_ROOM_BASE = 'https://www.cia.gov/readingroom';
const JFK_LIBRARY_BASE = 'https://www.jfklibrary.org';
const NARA_BERLIN_URL =
  'https://www.archives.gov/research/foreign-policy/cold-war/1961-berlin-crisis/nara-documents.html';
const STATE_FOIA_BASE = 'https://foia.state.gov';
const NSARCHIVE_BASE = 'https://nsarchive.gwu.edu';
const NSARCHIVE_BAY_OF_PIGS_2 = 'https://nsarchive2.gwu.edu/bayofpigs/press2.html';
const NSARCHIVE_BAY_OF_PIGS_3 = 'https://nsarchive2.gwu.edu/bayofpigs/press3.html';
const SITE_BASE = '/jfk-first-90-days';

const iscapPdf = (number) =>
  `https://www.archives.gov/files/declassification/iscap/pdf/2014-030-document-${number}-release-508-complete.pdf`;

const nsarchiveDocument = (path) => `${NSARCHIVE_BASE}${path}`;
const bayOfPigsPdf = (fileName) => `https://nsarchive2.gwu.edu/bayofpigs/${fileName}`;
const ciaReadingRoomDocument = (documentNumber) => `${CIA_READING_ROOM_BASE}/document/${documentNumber}`;
const ciaReadingRoomPdf = (fileName) => `${CIA_READING_ROOM_BASE}/docs/${fileName}`;
const ciaCibPdf = (pdfId) => ciaReadingRoomPdf(`CENTRAL%20INTELLIGENCE%20BULL%5B${pdfId}%5D.pdf`);
const jfkLibraryPage = (path) => `${JFK_LIBRARY_BASE}${path}`;
const naraCatalogRecord = (id) => `https://catalog.archives.gov/id/${id}`;
const stateFoiaCase = (caseNumber) =>
  `${STATE_FOIA_BASE}/FOIALIBRARY/SearchResults.aspx?caseNumber=${caseNumber}`;
const stateFoiaPdf = (path) => `${STATE_FOIA_BASE}/${path}`;
const nitzePdf = (fileName) => `${SITE_BASE}/documents/nitze/${fileName}`;

const iscapDefaults = {
  source: 'ISCAP',
  repository: 'Interagency Security Classification Appeals Panel',
  collection: 'ISCAP Appeals Log',
  container: '2014-030: Laos, 1961',
  section: 'Laos',
  documentType: 'ISCAP release',
  url: ISCAP_2014_030_URL,
  officialUrl: ISCAP_2014_030_URL,
  topics: ['Laos', 'Asia', 'Intelligence', 'Defense'],
  sourceNote:
    'Released through ISCAP appeal 2014-030 for records located at the John F. Kennedy Presidential Library and Museum.',
};

const nsarchiveDefaults = {
  source: 'National Security Archive',
  repository: 'National Security Archive, George Washington University',
  collection: 'National Security Archive Virtual Reading Room',
  documentType: 'National Security Archive document',
  officialUrl: 'https://nsarchive.gwu.edu/virtual-reading-room',
  sourceNote: 'Document page and PDF hosted by the National Security Archive.',
};

const bayOfPigsDefaults = {
  ...nsarchiveDefaults,
  collection: 'Bay of Pigs: 40 Years After',
  container: 'Bay of Pigs 40th anniversary release',
  section: 'Cuba and Bay of Pigs',
  documentType: 'National Security Archive Bay of Pigs release',
  topics: ['Bay of Pigs', 'Cuba', 'Latin America', 'Intelligence', 'Defense'],
  sourceNote: 'Released on the National Security Archive Bay of Pigs 40th anniversary website.',
};

const stateFoiaDefaults = {
  source: 'State FOIA',
  repository: 'U.S. Department of State',
  collection: 'Department of State FOIA Library',
  documentType: 'State FOIA release',
  topics: ['Diplomacy'],
  sourceNote:
    'Located through FOIA.state.gov search and microfiche indexes; direct PDF hosted by the Department of State FOIA Library.',
};

const ciaFoiaDefaults = {
  source: 'CIA FOIA',
  repository: 'Central Intelligence Agency',
  collection: 'CIA FOIA Electronic Reading Room',
  documentType: 'CIA FOIA release',
  topics: ['Intelligence'],
  officialUrl: `${CIA_READING_ROOM_BASE}/`,
  sourceNote: 'Located through the CIA FOIA Electronic Reading Room; direct PDF hosted by CIA.',
};

const ciaCibIssues = [
  ['1961-01-21', '02000177', 23, '15815782', '1.12 MB'],
  ['1961-01-23', '02000178', 16, '15815635', '833.72 KB'],
  ['1961-01-24', '02000179', 14, '15815639', '670.92 KB'],
  ['1961-01-25', '02000180', 17, '15815787', '786.36 KB'],
  ['1961-01-26', '02000181', 19, '15815554', '927.91 KB'],
  ['1961-01-27', '02000182', 19, '15815781', '841.29 KB'],
  ['1961-01-28', '02000183', 34, '15815742', '1.5 MB'],
  ['1961-01-30', '02000184', 20, '15815531', '938.34 KB'],
  ['1961-01-31', '02000185', 20, '15815598', '990.26 KB'],
  ['1961-02-01', '03174712', 15, '15815760', '748.74 KB'],
  ['1961-02-02', '06788696', 22, '15815637', '986.38 KB'],
  ['1961-02-03', '02000186', 20, '15815638', '937.26 KB'],
  ['1961-02-04', '02000187', 15, '15815578', '616.15 KB'],
  ['1961-02-06', '02000188', 25, '15815785', '1.16 MB'],
  ['1961-02-07', '02000189', 24, '15815623', '1.16 MB'],
  ['1961-02-09', '02000191', 18, '15815535', '753.94 KB'],
  ['1961-02-10', '02000192', 15, '15815791', '747.47 KB'],
  ['1961-02-11', '02000193', 17, '15815597', '843.37 KB'],
  ['1961-02-13', '02000194', 21, '15815741', '977.85 KB'],
  ['1961-02-14', '02000195', 17, '15815627', '695.58 KB'],
  ['1961-02-15', '02000196', 26, '15815532', '1.18 MB'],
  ['1961-02-16', '02000197', 19, '15815583', '813.02 KB'],
  ['1961-02-17', '02000198', 19, '15815784', '876.37 KB'],
  ['1961-02-18', '03172677', 20, '15815559', '963.23 KB'],
  ['1961-02-22', '03184172', 11, '15815556', '521.2 KB'],
  ['1961-02-23', '02026613', 21, '15815764', '1022.02 KB'],
  ['1961-02-24', '03007376', 14, '15815770', '607.91 KB'],
  ['1961-02-25', '03172678', 21, '15815631', '942.67 KB'],
  ['1961-02-27', '03172679', 24, '15815580', '1.27 MB'],
  ['1961-02-28', '02989742', 13, '15815789', '632.45 KB'],
  ['1961-03-02', '02026614', 16, '15815609', '838.94 KB'],
  ['1961-03-04', '02026616', 17, '15815744', '796.16 KB'],
  ['1961-03-08', '02026617', 19, '15815788', '901.13 KB'],
  ['1961-03-09', '03184093', 18, '15815793', '846.83 KB'],
  ['1961-03-10', '02001967', 16, '15815537', '731.22 KB'],
  ['1961-03-11', '03184094', 20, '15815797', '881.14 KB'],
  ['1961-03-13', '02001968', 18, '15815558', '773.93 KB'],
  ['1961-03-14', '02001969', 15, '15815534', '659.53 KB'],
  ['1961-03-15', '03007380', 21, '15815792', '1 MB'],
  ['1961-03-16', '03186011', 18, '15815762', '814.13 KB'],
  ['1961-03-17', '03007381', 19, '15815796', '931.19 KB'],
  ['1961-03-18', '03007382', 17, '15815799', '773.73 KB'],
  ['1961-03-20', '02001970', 20, '15815539', '988.96 KB'],
  ['1961-03-21', '03007383', 14, '15815585', '607.76 KB'],
  ['1961-03-22', '03007384', 19, '15815769', '1004 KB'],
  ['1961-03-23', '03007385', 21, '15815795', '989.13 KB'],
  ['1961-03-24', '02001971', 19, '15815749', '842.27 KB'],
  ['1961-03-25', '03007386', 16, '15815582', '616.34 KB'],
  ['1961-03-27', '02731969', 20, '15815536', '865.63 KB'],
  ['1961-03-28', '02001972', 12, '15815563', '610.59 KB'],
  ['1961-03-29', '02001973', 24, '15815773', '1.08 MB'],
  ['1961-03-30', '03007387', 18, '15815768', '869.59 KB'],
  ['1961-03-31', '03186012', 18, '15815743', '819.14 KB'],
  ['1961-04-01', '02001974', 20, '15815560', '880.9 KB'],
  ['1961-04-03', '02001975', 21, '15815541', '941.44 KB'],
  ['1961-04-04', '03186013', 15, '15815748', '617.31 KB'],
  ['1961-04-06', '02001977', 22, '15815772', '996.29 KB'],
  ['1961-04-07', '02001978', 19, '15815538', '805.86 KB'],
  ['1961-04-08', '06788695', 13, '15815555', '527.81 KB'],
  ['1961-04-10', '02001979', 21, '15815543', '880.23 KB'],
  ['1961-04-11', '02001980', 21, '15815798', '1.02 MB'],
  ['1961-04-12', '02001981', 21, '15815540', '850.49 KB'],
  ['1961-04-13', '02001982', 22, '15815613', '1.11 MB'],
  ['1961-04-14', '02001983', 23, '15815608', '1.01 MB'],
  ['1961-04-15', '02001984', 23, '15815612', '1.07 MB'],
  ['1961-04-17', '02001985', 16, '15815746', '766.43 KB'],
  ['1961-04-18', '02001986', 23, '15815545', '1.03 MB'],
  ['1961-04-19', '02001987', 22, '15815617', '1.1 MB'],
  ['1961-04-20', '02001988', 18, '15815751', '798.77 KB'],
];

const ciaCibRecords = ciaCibIssues.map(([date, documentNumber, pages, pdfId, size]) => ({
  ...ciaFoiaDefaults,
  id: `cia-cib-${date}`,
  title: `Central Intelligence Bulletin - ${date}`,
  date,
  container: 'Current/Central Intelligence Bulletin, 2 January-30 June 1961',
  section: 'Daily intelligence briefings',
  documentNumber: `CIA document ${documentNumber}`,
  documentType: 'Central Intelligence Bulletin',
  topics: ['Intelligence', 'USSR', 'Laos', 'Congo', 'Cuba', 'Defense', 'Diplomacy'],
  url: ciaCibPdf(pdfId),
  officialUrl: ciaReadingRoomDocument(documentNumber),
  dataUrl: ciaCibPdf(pdfId),
  citation: `Central Intelligence Bulletin, ${date}, CIA FOIA Reading Room, document ${documentNumber}.`,
  summary:
    "Daily CIA intelligence digest in the 2 January-30 June 1961 CIB release, covering Kennedy-era foreign-policy crises including Laos, Congo, Soviet military and space developments, and Cuba.",
  sourceNote: `CIA Reading Room PDF in the Current/Central Intelligence Bulletin collection (${pages} pages, ${size}).`,
}));

const ciaBayOfPigsRecords = [
  {
    id: 'cia-bay-of-pigs-vol1-part1',
    title: 'Official History of the Bay of Pigs Operation, Volume I, Part 1',
    documentNumber: '5076ddc4993247d4d82b58d9',
    pdfFile: 'bop-vol1-part1.pdf',
    size: '11.61 MB',
    summary:
      'CIA staff history volume section on air operations for the Bay of Pigs operation, covering March 1960-April 1961.',
  },
  {
    id: 'cia-bay-of-pigs-vol1-part2',
    title: 'Official History of the Bay of Pigs Operation, Volume I, Part 2',
    documentNumber: '5076ddc4993247d4d82b58da',
    pdfFile: 'bop-vol1-part2.pdf',
    size: '6.86 MB',
    summary:
      'Continuation of the CIA staff history on air operations for the Bay of Pigs operation and its April 1961 execution.',
  },
  {
    id: 'cia-bay-of-pigs-vol1-part3',
    title: 'Official History of the Bay of Pigs Operation, Volume I, Part 3',
    documentNumber: '5076ddc4993247d4d82b58d6',
    pdfFile: 'bop-vol1-part3.pdf',
    size: '2.61 MB',
    summary:
      'Final section of the CIA staff history volume on air operations for the Bay of Pigs invasion.',
  },
  {
    id: 'cia-bay-of-pigs-vol2-part1',
    title: 'Official History of the Bay of Pigs Operation, Volume II, Part 1',
    documentNumber: '5076ddc4993247d4d82b58d5',
    pdfFile: 'bop-vol2-part1.pdf',
    size: '5.73 MB',
    summary:
      'CIA staff history volume on participation in the conduct of foreign policy during the Bay of Pigs operation.',
  },
  {
    id: 'cia-bay-of-pigs-vol2-part2',
    title: 'Official History of the Bay of Pigs Operation, Volume II, Part 2',
    documentNumber: '5076ddc4993247d4d82b58d7',
    pdfFile: 'bop-vol2-part2.pdf',
    size: '2.36 MB',
    summary:
      'Continuation of the CIA staff history on policy participation and high-level decision-making around the Bay of Pigs operation.',
  },
  {
    id: 'cia-bay-of-pigs-vol3',
    title: 'Official History of the Bay of Pigs Operation, Volume III',
    documentNumber: '5076ddc4993247d4d82b58d4',
    pdfFile: 'bop-vol3.pdf',
    size: '14.14 MB',
    summary:
      'CIA staff history volume on the evolution of CIA anti-Castro policies through January 1961, giving transition context for Kennedy-era Cuba policy.',
  },
  {
    id: 'cia-bay-of-pigs-vol4',
    title: 'Official History of the Bay of Pigs Operation, Volume IV',
    documentNumber: '5076ddc4993247d4d82b58d8',
    pdfFile: 'bop-vol4.pdf',
    size: '11.39 MB',
    summary:
      'CIA staff history volume on the Taylor Committee investigation into the Bay of Pigs failure.',
  },
  {
    id: 'cia-bay-of-pigs-vol5-draft',
    title: "Official History of the Bay of Pigs Operation, Draft Volume V: CIA's Internal Investigation",
    documentNumber: '0001254908',
    pdfFile: 'C01254908.pdf',
    size: '8.4 MB',
    summary:
      "Draft CIA staff history volume on the agency's internal investigation of the Bay of Pigs operation.",
  },
].map((record) => ({
  ...ciaFoiaDefaults,
  id: record.id,
  title: record.title,
  date: '',
  displayDate: 'CIA official history; covers Bay of Pigs, 1960-1961',
  container: 'Bay of Pigs Release',
  section: 'Cuba and Bay of Pigs',
  documentNumber: `CIA document ${record.documentNumber}`,
  documentType: 'CIA official history',
  topics: ['Bay of Pigs', 'Cuba', 'Latin America', 'Intelligence', 'Defense', 'Diplomacy'],
  url: ciaReadingRoomPdf(record.pdfFile),
  officialUrl: ciaReadingRoomDocument(record.documentNumber),
  dataUrl: ciaReadingRoomPdf(record.pdfFile),
  citation: `CIA FOIA Reading Room, Bay of Pigs Release, ${record.title}.`,
  summary: record.summary,
  sourceNote: `CIA Bay of Pigs Release PDF (${record.size}).`,
}));

const jfkLibraryDefaults = {
  source: 'JFK Library',
  repository: 'John F. Kennedy Presidential Library and Museum',
  collection: 'JFK Library Digital Archives',
  documentType: 'JFK Library digital folder',
  sourceNote: 'Digitized record page hosted by the John F. Kennedy Presidential Library and Museum.',
};

const jfkPressConferenceRecords = [
  {
    id: 'jfk-library-news-conference-1',
    title: 'News Conference 1, January 25, 1961',
    date: '1961-01-25',
    url: jfkLibraryPage('/archives/other-resources/john-f-kennedy-press-conferences/news-conference-1'),
    summary:
      'Official transcript of Kennedy press conference covering nuclear test-ban negotiations, Congo famine relief, Cuba, and communications with Khrushchev.',
    topics: ['Nuclear', 'Congo', 'Cuba', 'USSR', 'Laos', 'Diplomacy'],
  },
  {
    id: 'jfk-library-news-conference-2',
    title: 'News Conference 2, February 1, 1961',
    date: '1961-02-01',
    url: jfkLibraryPage('/archives/other-resources/john-f-kennedy-press-conferences/news-conference-2'),
    summary:
      'Official transcript of Kennedy press conference with early-administration questions on foreign affairs and national security.',
    topics: ['Diplomacy', 'Defense', 'USSR', 'Cuba'],
  },
  {
    id: 'jfk-library-news-conference-3',
    title: 'News Conference 3, February 8, 1961',
    date: '1961-02-08',
    url: jfkLibraryPage('/archives/other-resources/john-f-kennedy-press-conferences/news-conference-3'),
    summary:
      'Official transcript including Kennedy on relations with the Soviet Union, Laos, Congo, Communist China, and the State of the Union warning about international danger.',
    topics: ['USSR', 'Laos', 'Congo', 'Asia', 'Diplomacy', 'Defense'],
  },
  {
    id: 'jfk-library-news-conference-4',
    title: 'News Conference 4, February 15, 1961',
    date: '1961-02-15',
    url: jfkLibraryPage('/archives/other-resources/john-f-kennedy-press-conferences/news-conference-4'),
    summary:
      'Official transcript from Kennedy press conference during the early Laos, Congo, Cuba, and disarmament policy period.',
    topics: ['Laos', 'Congo', 'Cuba', 'Nuclear', 'Diplomacy'],
  },
  {
    id: 'jfk-library-news-conference-5',
    title: 'News Conference 5, March 1, 1961',
    date: '1961-03-01',
    url: jfkLibraryPage('/archives/other-resources/john-f-kennedy-press-conferences/news-conference-5'),
    summary:
      'Official transcript including announcements on Chancellor Adenauer, the Peace Corps, and questions on Congo, nuclear disarmament, and U.S.-Soviet relations.',
    topics: ['Berlin', 'NATO', 'Peace Corps', 'Congo', 'Nuclear', 'USSR', 'Diplomacy'],
  },
  {
    id: 'jfk-library-news-conference-6',
    title: 'News Conference 6, March 8, 1961',
    date: '1961-03-08',
    url: jfkLibraryPage('/archives/other-resources/john-f-kennedy-press-conferences/news-conference-6'),
    summary:
      'Official transcript including Radio Free Europe, Latin America, Cuba, Laos, and foreign-policy questions before the Alliance for Progress address.',
    topics: ['Europe', 'Latin America', 'Cuba', 'Laos', 'USSR', 'Diplomacy'],
  },
  {
    id: 'jfk-library-news-conference-7',
    title: 'News Conference 7, March 15, 1961',
    date: '1961-03-15',
    url: jfkLibraryPage('/archives/other-resources/john-f-kennedy-press-conferences/news-conference-7'),
    summary:
      'Official transcript covering the Canada treaty announcement, Israel credit, United Nations, disarmament, test ban, Laos, Latin America, and Geneva talks.',
    topics: ['Nuclear', 'United Nations', 'Laos', 'Latin America', 'Middle East', 'NATO', 'Diplomacy'],
  },
  {
    id: 'jfk-library-news-conference-8',
    title: 'News Conference 8, March 23, 1961',
    date: '1961-03-23',
    url: jfkLibraryPage('/archives/other-resources/john-f-kennedy-press-conferences/news-conference-8'),
    summary:
      'Official transcript of Kennedy press conference opening with a major statement on Laos and answering questions on Laos, foreign aid, and related policy.',
    topics: ['Laos', 'Foreign Aid', 'Asia', 'Diplomacy', 'Defense'],
  },
  {
    id: 'jfk-library-news-conference-9',
    title: 'News Conference 9, April 12, 1961',
    date: '1961-04-12',
    url: jfkLibraryPage('/archives/other-resources/john-f-kennedy-press-conferences/news-conference-9'),
    summary:
      'Official transcript including the foreign-aid advisory group, Cuba, Yuri Gagarin and Soviet space achievement, Red China and the United Nations, Taiwan, and Laos.',
    topics: ['Foreign Aid', 'Cuba', 'USSR', 'Asia', 'United Nations', 'Laos', 'Diplomacy'],
  },
].map((record) => ({
  ...jfkLibraryDefaults,
  ...record,
  container: 'JFK press conferences',
  section: 'Public statements and transcripts',
  documentNumber: record.id.replace('jfk-library-news-conference-', 'News Conference '),
  documentType: 'JFK press conference transcript',
  officialUrl: record.url,
  dataUrl: record.url,
  citation: `John F. Kennedy Presidential Library, ${record.title}.`,
}));

const jfkSpeechRecords = [
  {
    id: 'jfk-library-inaugural-address-19610120',
    title: 'Inaugural Address, January 20, 1961',
    date: '1961-01-20',
    url: jfkLibraryPage('/archives/other-resources/john-f-kennedy-speeches/inaugural-address-19610120'),
    summary:
      'Official JFK Library transcript of Kennedy foreign-policy pledges to allies, new states, Latin America, the United Nations, and adversaries in the nuclear age.',
    topics: ['USSR', 'Nuclear', 'United Nations', 'Latin America', 'Foreign Aid', 'Diplomacy'],
  },
  {
    id: 'jfk-library-state-of-union-19610130',
    title: 'State of the Union Message, 30 January 1961',
    date: '1961-01-30',
    url: jfkLibraryPage('/asset-viewer/archives/blbpp-mf10-012'),
    summary:
      'JFK Library digitized booklet of Kennedy January 30, 1961 State of the Union message, a public statement framing the early foreign-policy agenda.',
    topics: ['Diplomacy', 'Defense', 'Foreign Aid', 'Nuclear', 'USSR'],
  },
  {
    id: 'jfk-library-alliance-for-progress-address-19610313',
    title: 'Address to Latin American diplomats announcing the Alliance for Progress',
    date: '1961-03-13',
    url: jfkLibraryPage(
      '/archives/other-resources/john-f-kennedy-speeches/latin-american-diplomats-washington-dc-19610313',
    ),
    summary:
      'Official JFK Library transcript of Kennedy remarks outlining the Alliance for Progress and a hemispheric program for development and democratic reform.',
    topics: ['Latin America', 'Foreign Aid', 'Cuba', 'Diplomacy'],
  },
].map((record) => ({
  ...jfkLibraryDefaults,
  ...record,
  container: 'JFK speeches',
  section: 'Public statements and transcripts',
  documentNumber: record.id.replace('jfk-library-', ''),
  documentType: 'JFK speech transcript',
  officialUrl: record.url,
  dataUrl: record.url,
  citation: `John F. Kennedy Presidential Library, ${record.title}.`,
}));

const jfkFolderRecords = [
  {
    id: 'jfk-library-pof-press-conference-19610125',
    title: 'President Office Files: 25 January 1961 press conference folder',
    date: '1961-01-23',
    endDate: '1961-01-25',
    displayDate: 'January 23-25, 1961',
    documentNumber: 'JFKPOF-054-001',
    url: jfkLibraryPage('/asset-viewer/archives/jfkpof-054-001'),
    container: 'President Office Files, Press Conferences',
    section: 'Press conferences',
    summary:
      'Folder of briefing materials and transcripts for News Conference 1, including nuclear test-ban talks, Congo famine relief, Laos, Cuba, and Khrushchev communications.',
    topics: ['Nuclear', 'Congo', 'Laos', 'Cuba', 'USSR', 'Diplomacy'],
  },
  {
    id: 'jfk-library-pof-press-conference-19610308',
    title: 'President Office Files: 8 March 1961 press conference folder',
    date: '1961-03-08',
    documentNumber: 'JFKPOF-054-008',
    url: jfkLibraryPage('/asset-viewer/archives/jfkpof-054-008'),
    container: 'President Office Files, Press Conferences',
    section: 'Press conferences',
    summary:
      'Briefing-material folder for News Conference 6 with nuclear weapons and disarmament, NATO, U.S.-Soviet relations, Congo, Laos, and U.S.-Cuban relations.',
    topics: ['Nuclear', 'NATO', 'USSR', 'Congo', 'Laos', 'Cuba', 'Diplomacy'],
  },
  {
    id: 'jfk-library-pof-cia-1961-jan-may',
    title: 'Central Intelligence Agency (CIA), 1961: January-May',
    date: '1961-02-11',
    endDate: '1961-05-06',
    displayDate: 'February-May 1961',
    documentNumber: 'JFKPOF-072-002',
    url: jfkLibraryPage('/asset-viewer/archives/jfkpof-072-002'),
    container: "President's Office Files",
    section: 'Departments and agencies',
    summary:
      'Folder on CIA materials, including CIA Bulletins on Laos, Congo, Soviet Union, Libya, France and Algeria, and possible U.S. courses of action against Castro.',
    topics: ['Intelligence', 'Laos', 'Congo', 'USSR', 'Africa', 'Cuba', 'Defense'],
  },
  {
    id: 'jfk-library-nsf-vietnam-1961-jan-mar',
    title: 'Vietnam: General, 1961: January-March',
    date: '1961-01-27',
    endDate: '1961-03-29',
    displayDate: 'January-March 1961',
    documentNumber: 'JFKNSF-193-004',
    url: jfkLibraryPage('/asset-viewer/archives/jfknsf-193-004'),
    container: 'National Security Files, Countries',
    section: 'Vietnam',
    summary:
      'Folder of telegrams and memoranda on Vietnam, including counterinsurgency planning, Cambodia-Laos-Thailand relations, communism in the region, and Kenneth Young reporting.',
    topics: ['Vietnam', 'Laos', 'Asia', 'Defense', 'Diplomacy'],
  },
  {
    id: 'jfk-library-nsf-cuba-1961-jan-apr',
    title: 'Cuba: General, 1961: January-April',
    date: '1961-01-27',
    endDate: '1961-04-28',
    displayDate: 'January-April 1961',
    documentNumber: 'JFKNSF-035-017',
    url: jfkLibraryPage('/asset-viewer/archives/jfknsf-035-017'),
    container: 'National Security Files, Countries',
    section: 'Cuba',
    summary:
      'Folder of Cuba memoranda, including Bay of Pigs planning, OAS questions, U.S. Cuba policy, Castro, and Schlesinger memorandum on political, diplomatic, and economic problems.',
    topics: ['Cuba', 'Bay of Pigs', 'Latin America', 'Intelligence', 'Defense', 'Diplomacy'],
  },
  {
    id: 'jfk-library-nsf-laos-general-19610320',
    title: 'Laos: General, March 1961: 20-22',
    date: '1961-03-20',
    endDate: '1961-03-22',
    displayDate: 'March 20-22, 1961',
    documentNumber: 'JFKNSF-130-010',
    url: jfkLibraryPage('/asset-viewer/archives/jfknsf-130-010'),
    container: 'National Security Files, Countries',
    section: 'Laos',
    summary:
      'Folder of correspondence and memoranda on Laos surrounding Kennedy March 23 press conference and the neutral Laos policy crisis.',
    topics: ['Laos', 'Asia', 'Defense', 'Diplomacy'],
  },
  {
    id: 'jfk-library-pof-laos-security-19610401',
    title: 'Laos: Security, April 1961: 1-20',
    date: '1961-04-01',
    endDate: '1961-04-17',
    displayDate: 'April 1-17, 1961',
    documentNumber: 'JFKPOF-121a-005',
    url: jfkLibraryPage('/asset-viewer/archives/jfkpof-121a-005'),
    container: "President's Office Files",
    section: 'Laos',
    summary:
      "Folder collected by Evelyn Lincoln concerning Laotian neutrality and the possibility of a Soviet-supported Pathet Lao rebellion.",
    topics: ['Laos', 'Asia', 'USSR', 'Defense', 'Diplomacy'],
  },
  {
    id: 'jfk-library-nsf-uar-nasser-1961-jan-apr',
    title: 'United Arab Republic: Nasser correspondence, 1961: 20 January-30 April',
    date: '1961-01-20',
    endDate: '1961-04-30',
    displayDate: 'January-April 1961',
    documentNumber: 'JFKNSF-169-003',
    url: jfkLibraryPage('/asset-viewer/archives/jfknsf-169-003'),
    container: 'National Security Files, Countries',
    section: 'United Arab Republic',
    summary:
      'Folder of memoranda and correspondence between the State Department, Kennedy, and Gamal Abdel Nasser on U.S. foreign policy, Congo, United Nations response, and Cuba.',
    topics: ['Middle East', 'Africa', 'Congo', 'Cuba', 'United Nations', 'Diplomacy'],
  },
  {
    id: 'jfk-library-nsf-bowles-1961-jan-apr',
    title: 'Staff memoranda: Bowles, Chester, 1961: January-April',
    date: '1961-02-12',
    endDate: '1961-04-14',
    displayDate: 'February-April 1961',
    documentNumber: 'JFKNSF-319a-003',
    url: jfkLibraryPage('/asset-viewer/archives/jfknsf-319a-003'),
    container: 'National Security Files, Meetings and Memoranda',
    section: 'Staff memoranda',
    summary:
      'Folder with Chester Bowles-related materials on Peace Corps concerns in Nigeria and an Indo-American development program paper.',
    topics: ['Peace Corps', 'Foreign Aid', 'Africa', 'Asia', 'Diplomacy'],
  },
  {
    id: 'jfk-library-nsf-alliance-for-progress-1961',
    title: 'Alliance for Progress: General, 1961: January-December',
    date: '1961-03-06',
    endDate: '1961-11-17',
    displayDate: 'March-November 1961',
    documentNumber: 'JFKNSF-290-019',
    url: jfkLibraryPage('/asset-viewer/archives/jfknsf-290-019'),
    container: 'National Security Files, Subjects',
    section: 'Alliance for Progress',
    summary:
      'Folder of memoranda, correspondence, an address, and press release on creating and managing the Alliance for Progress foreign-aid initiative in Latin America.',
    topics: ['Latin America', 'Foreign Aid', 'Diplomacy'],
  },
  {
    id: 'jfk-library-nsf-foreign-aid-1961-mar-apr',
    title: 'Foreign aid: General, 1961: March-April',
    date: '1961-02-03',
    endDate: '1961-04-26',
    displayDate: 'February-April 1961',
    documentNumber: 'JFKNSF-297-002',
    url: jfkLibraryPage('/asset-viewer/archives/jfknsf-297-002'),
    container: 'National Security Files, Subjects',
    section: 'Foreign aid',
    summary:
      'Folder of press release and memoranda concerning an Emergency Freedom Fund and reorganization and funding of the U.S. foreign-aid program.',
    topics: ['Foreign Aid', 'Diplomacy', 'Defense'],
  },
  {
    id: 'jfk-library-nsf-presidents-speeches-1961',
    title: "President's speeches: miscellaneous drafts and comments, 1961-1963",
    date: '1961-03-18',
    endDate: '1963-11-05',
    displayDate: 'March 1961-November 1963',
    documentNumber: 'JFKNSF-305-004',
    url: jfkLibraryPage('/asset-viewer/archives/jfknsf-305-004'),
    container: 'National Security Files, Subjects',
    section: 'Presidential speeches',
    summary:
      'Folder of letters, memoranda, and speech drafts on foreign aid, communism, nuclear weapons, international relations, Berlin, Cuba, the Soviet Union, and Latin America.',
    topics: ['Foreign Aid', 'Nuclear', 'Berlin', 'Cuba', 'USSR', 'Latin America', 'Diplomacy'],
  },
].map((record) => ({
  ...jfkLibraryDefaults,
  ...record,
  officialUrl: record.url,
  dataUrl: record.url,
  citation: `John F. Kennedy Presidential Library, ${record.title}, ${record.documentNumber}.`,
}));

const naraBerlinRecords = [
  {
    id: 'nara-berlin-6036974',
    title:
      'Report of the Four-Power Working Group on Germany Including Berlin on planning for a separate peace treaty',
    date: '1961-03-03',
    documentNumber: '6036974',
    url: 'https://nara-media-001.s3.amazonaws.com/arcmedia/research/1961-berlin-crisis/959001-6-6-untabbed/95901-6-6.pdf',
    summary:
      'NARA Berlin Crisis PDF on quadripartite planning for a possible Soviet-GDR separate peace treaty and Berlin contingency issues.',
  },
  {
    id: 'nara-berlin-6035203',
    title: 'Clandestine Action in Support of the U.S. Berlin Policy',
    date: '1961-03-23',
    documentNumber: '6035203',
    url: 'https://nara-media-001.s3.amazonaws.com/arcmedia/research/1961-berlin-crisis/32229-2-3-6/32229-2-3-6.pdf',
    summary:
      'NARA Berlin Crisis PDF on clandestine support for U.S. Berlin policy during early Kennedy contingency planning.',
  },
  {
    id: 'nara-berlin-6036997',
    title: 'Memorandum of Conversation: European Integration and the Six and Seven Problem',
    date: '1961-04-13',
    documentNumber: '6036997',
    url: 'https://nara-media-001.s3.amazonaws.com/arcmedia/research/1961-berlin-crisis/941139-1-3-36/941139-1-3-36.pdf',
    summary:
      'NARA Berlin Crisis PDF of an April 13 memorandum of conversation on European integration and the Six and Seven problem.',
  },
].map((record) => ({
  source: 'NARA Catalog',
  repository: 'National Archives and Records Administration',
  collection: 'Berlin Crisis of 1961: Documents at the National Archives',
  container: 'Berlin Crisis of 1961 documents',
  section: 'Berlin Crisis',
  documentType: 'NARA Berlin Crisis release',
  topics: ['Berlin', 'Europe', 'NATO', 'USSR', 'Diplomacy', 'Defense', 'Intelligence'],
  sourceNote: 'PDF listed on the National Archives Berlin Crisis of 1961 documents page.',
  ...record,
  officialUrl: naraCatalogRecord(record.documentNumber),
  dataUrl: record.url,
  citation: `National Archives, Berlin Crisis of 1961 documents, National Archives Identifier ${record.documentNumber}.`,
}));

const nitzeDefaults = {
  source: 'Nitze Interviews',
  repository: 'Paul H. Nitze interview files',
  collection: 'Nitze oral-history and interview PDFs',
  container: 'Local OCR search results',
  section: 'Kennedy foreign policy, first 90 days',
  documentType: 'Nitze interview PDF',
  topics: ['Defense', 'Diplomacy'],
  sourceNote:
    'Local PDF copy selected from the Nitze OCR search because it contains interview material on Kennedy foreign-policy work during January-April 1961.',
};

export const supplementalRecords = [
  ...ciaCibRecords,
  ...ciaBayOfPigsRecords,
  ...jfkPressConferenceRecords,
  ...jfkSpeechRecords,
  ...jfkFolderRecords,
  ...naraBerlinRecords,
  {
    ...iscapDefaults,
    id: 'iscap-2014-030-doc-1',
    title: 'Letter to Chester Clifton from Allen Dulles',
    date: '1961-02-20',
    documentNumber: '2014-030-doc 1',
    dataUrl: iscapPdf(1),
    citation: 'ISCAP Appeal 2014-030, document 1. Letter to Chester Clifton from Allen Dulles, February 20, 1961.',
    summary: 'Declassified CIA-related correspondence from Allen Dulles to Brig. Gen. Chester V. Clifton concerning Laos and related regional policy.',
  },
  {
    ...stateFoiaDefaults,
    id: 'state-foia-f199603635-doc1',
    title: 'Briefings and early reassessments of the CIA Cuba Project',
    date: '1961-01-23',
    endDate: '1961-03-31',
    displayDate: 'January-March 1961',
    container: 'F-1996-03635: Bay of Pigs, Cuba from 1/61 to 9/62',
    section: 'Cuba and Bay of Pigs',
    documentNumber: 'F-1996-03635 doc 1',
    topics: ['Bay of Pigs', 'Cuba', 'Intelligence', 'Defense'],
    url: stateFoiaPdf('DOCUMENTS/FOIA_Micro_Final_6/F-1996-03635/DOC_0C09000001/C09000001.pdf'),
    officialUrl: stateFoiaCase('F-1996-03635'),
    dataUrl: stateFoiaPdf('DOCUMENTS/FOIA_Micro_Final_6/F-1996-03635/DOC_0C09000001/C09000001.pdf'),
    citation:
      'Department of State FOIA Library, case F-1996-03635, document 1, Briefings and Early Reassessments of the CIA Cuba Project by the Kennedy Administration, January-March 1961.',
    summary:
      'FOIA microfiche PDF containing Cuba Project briefing and reassessment documents from the opening weeks of the Kennedy administration.',
  },
  {
    ...stateFoiaDefaults,
    id: 'state-foia-f199603635-doc2',
    title: 'Reactions to and revisions of the CIA revised paramilitary plan for Cuba',
    date: '1961-03-15',
    endDate: '1961-04-16',
    displayDate: 'March-April 1961',
    container: 'F-1996-03635: Bay of Pigs, Cuba from 1/61 to 9/62',
    section: 'Cuba and Bay of Pigs',
    documentNumber: 'F-1996-03635 doc 2',
    topics: ['Bay of Pigs', 'Cuba', 'Intelligence', 'Defense'],
    url: stateFoiaPdf('DOCUMENTS/FOIA_Micro_Final_6/F-1996-03635/DOC_0C09000002/C09000002.pdf'),
    officialUrl: stateFoiaCase('F-1996-03635'),
    dataUrl: stateFoiaPdf('DOCUMENTS/FOIA_Micro_Final_6/F-1996-03635/DOC_0C09000002/C09000002.pdf'),
    citation:
      'Department of State FOIA Library, case F-1996-03635, document 2, Reactions to and Revisions of the CIA Revised Para-Military Plan for an Invasion at the Bay of Pigs, March-April 1961.',
    summary:
      'State FOIA PDF covering March-April 1961 revisions to the CIA paramilitary plan for the Cuba operation.',
  },
  {
    ...stateFoiaDefaults,
    id: 'state-foia-f199603635-doc3',
    title: 'Final decisions and the invasion of Cuba by the Cuban Brigade',
    date: '1961-04-07',
    endDate: '1961-04-17',
    displayDate: 'April 7-17, 1961',
    container: 'F-1996-03635: Bay of Pigs, Cuba from 1/61 to 9/62',
    section: 'Cuba and Bay of Pigs',
    documentNumber: 'F-1996-03635 doc 3',
    topics: ['Bay of Pigs', 'Cuba', 'Intelligence', 'Defense'],
    url: stateFoiaPdf('DOCUMENTS/FOIA_Micro_Final_6/F-1996-03635/DOC_0C09000003/C09000003.pdf'),
    officialUrl: stateFoiaCase('F-1996-03635'),
    dataUrl: stateFoiaPdf('DOCUMENTS/FOIA_Micro_Final_6/F-1996-03635/DOC_0C09000003/C09000003.pdf'),
    citation:
      'Department of State FOIA Library, case F-1996-03635, document 3, Final Decisions and the Invasion of Cuba by the Cuban Brigade at the Bay of Pigs, April 1961.',
    summary:
      'State FOIA PDF containing final decision documents, including April 7 and April 10 materials, for the Bay of Pigs operation.',
  },
  {
    ...stateFoiaDefaults,
    id: 'state-foia-f199603635-doc4',
    title: 'Reports and meetings assessing the Bay of Pigs failure',
    date: '1961-04-17',
    endDate: '1961-05-31',
    displayDate: 'April-May 1961',
    container: 'F-1996-03635: Bay of Pigs, Cuba from 1/61 to 9/62',
    section: 'Cuba and Bay of Pigs',
    documentNumber: 'F-1996-03635 doc 4',
    topics: ['Bay of Pigs', 'Cuba', 'Intelligence', 'Defense'],
    url: stateFoiaPdf('DOCUMENTS/FOIA_Micro_Final_6/F-1996-03635/DOC_0C09000004/C09000004.pdf'),
    officialUrl: stateFoiaCase('F-1996-03635'),
    dataUrl: stateFoiaPdf('DOCUMENTS/FOIA_Micro_Final_6/F-1996-03635/DOC_0C09000004/C09000004.pdf'),
    citation:
      'Department of State FOIA Library, case F-1996-03635, document 4, Reports and Meetings Assessing the Failure of the Bay of Pigs Operation, April-May 1961.',
    summary:
      'State FOIA PDF with April 17 and later reporting and meeting records assessing the failed Cuba operation.',
  },
  {
    ...stateFoiaDefaults,
    id: 'state-foia-f199202535-doc1',
    title: 'Memorandum of conversation: Diefenbaker visit',
    date: '1961-02-20',
    container: 'F-1992-02535: 1961 nuclear weapons and Minuteman correspondence',
    section: 'Canada, NATO, and nuclear policy',
    documentNumber: 'F-1992-02535 doc 1',
    topics: ['NATO', 'Nuclear', 'Defense', 'Diplomacy'],
    url: stateFoiaPdf('DOCUMENTS/FOIA_Micro_Final_2/F-1992-02535/DOC_0C09000001/C09000001.pdf'),
    officialUrl: stateFoiaCase('F-1992-02535'),
    dataUrl: stateFoiaPdf('DOCUMENTS/FOIA_Micro_Final_2/F-1992-02535/DOC_0C09000001/C09000001.pdf'),
    citation:
      'Department of State FOIA Library, case F-1992-02535, document 1, Memorandum of Conversation, Diefenbaker Visit, February 20, 1961.',
    summary:
      "White House memorandum of conversation from Canadian Prime Minister John Diefenbaker's February 1961 visit, released in a State FOIA case on 1961 nuclear weapons and Minuteman correspondence.",
  },
  {
    ...stateFoiaDefaults,
    id: 'state-foia-f199202535-doc2',
    title: 'Memorandum of conversation: NATO',
    date: '1961-02-21',
    container: 'F-1992-02535: 1961 nuclear weapons and Minuteman correspondence',
    section: 'NATO and nuclear policy',
    documentNumber: 'F-1992-02535 doc 2',
    topics: ['NATO', 'Nuclear', 'Defense', 'Diplomacy'],
    url: stateFoiaPdf('DOCUMENTS/FOIA_Micro_Final_2/F-1992-02535/DOC_0C09000002/C09000002.pdf'),
    officialUrl: stateFoiaCase('F-1992-02535'),
    dataUrl: stateFoiaPdf('DOCUMENTS/FOIA_Micro_Final_2/F-1992-02535/DOC_0C09000002/C09000002.pdf'),
    citation:
      'Department of State FOIA Library, case F-1992-02535, document 2, Memorandum of Conversation, NATO, February 21, 1961.',
    summary:
      'State FOIA memorandum of conversation on NATO from February 21, 1961, in the Kennedy administration nuclear-policy case file.',
  },
  {
    ...stateFoiaDefaults,
    id: 'state-foia-f199202535-doc3',
    title: 'Memorandum of conversation: Adenauer visit, NATO and East-West relations',
    date: '1961-04-12',
    container: 'F-1992-02535: 1961 nuclear weapons and Minuteman correspondence',
    section: 'Germany, NATO, and East-West relations',
    documentNumber: 'F-1992-02535 doc 3',
    topics: ['NATO', 'Berlin', 'Nuclear', 'Diplomacy'],
    url: stateFoiaPdf('DOCUMENTS/FOIA_Micro_Final_2/F-1992-02535/DOC_0C09000003/C09000003.pdf'),
    officialUrl: stateFoiaCase('F-1992-02535'),
    dataUrl: stateFoiaPdf('DOCUMENTS/FOIA_Micro_Final_2/F-1992-02535/DOC_0C09000003/C09000003.pdf'),
    citation:
      'Department of State FOIA Library, case F-1992-02535, document 3, Memorandum of Conversation, Adenauer Visit, NATO and East-West Relations, April 12, 1961.',
    summary:
      'White House memorandum of conversation with Chancellor Adenauer covering NATO and East-West relations during the April 1961 visit.',
  },
  {
    ...stateFoiaDefaults,
    id: 'state-foia-f199202535-doc4',
    title: 'Memorandum of conversation: Adenauer visit and NATO nuclear questions',
    date: '1961-04-12',
    container: 'F-1992-02535: 1961 nuclear weapons and Minuteman correspondence',
    section: 'Germany, NATO, and nuclear policy',
    documentNumber: 'F-1992-02535 doc 4',
    topics: ['NATO', 'Berlin', 'Nuclear', 'Diplomacy'],
    url: stateFoiaPdf('DOCUMENTS/FOIA_Micro_Final_2/F-1992-02535/DOC_0C09000004/C09000004.pdf'),
    officialUrl: stateFoiaCase('F-1992-02535'),
    dataUrl: stateFoiaPdf('DOCUMENTS/FOIA_Micro_Final_2/F-1992-02535/DOC_0C09000004/C09000004.pdf'),
    citation:
      'Department of State FOIA Library, case F-1992-02535, document 4, Memorandum of Conversation, Adenauer Visit, April 12, 1961.',
    summary:
      'Additional State FOIA memorandum from the Adenauer visit touching NATO, Germany, and early Kennedy nuclear-policy questions.',
  },
  {
    ...stateFoiaDefaults,
    id: 'state-foia-f198201141-doc83',
    title: 'Telegram from Saigon reporting signature of U.S.-Viet-Nam treaty',
    date: '1961-04-03',
    container: 'F-1982-01141: FCN agreement, U.S.-Vietnam',
    section: 'Vietnam and treaty relations',
    documentNumber: 'F-1982-01141 doc 83',
    topics: ['Vietnam', 'Asia', 'Diplomacy'],
    url: stateFoiaPdf('DOCUMENTS/FOIA_Micro_June2024/F-1982-01141/DOC_0C09000083/C09000083.pdf'),
    officialUrl: stateFoiaCase('F-1982-01141'),
    dataUrl: stateFoiaPdf('DOCUMENTS/FOIA_Micro_June2024/F-1982-01141/DOC_0C09000083/C09000083.pdf'),
    citation:
      'Department of State FOIA Library, case F-1982-01141, document 83, Telegram from Saigon, April 3, 1961.',
    summary:
      'Incoming State Department telegram from Saigon reporting signature of the Treaty of Amity and Economic Relations with the Republic of Viet-Nam.',
  },
  {
    ...stateFoiaDefaults,
    id: 'state-foia-f198201141-doc85',
    title: 'Treaty of Amity and Economic Relations between the United States and Viet-Nam',
    date: '1961-04-03',
    container: 'F-1982-01141: FCN agreement, U.S.-Vietnam',
    section: 'Vietnam and treaty relations',
    documentNumber: 'F-1982-01141 doc 85',
    topics: ['Vietnam', 'Asia', 'Diplomacy'],
    url: stateFoiaPdf('DOCUMENTS/FOIA_Micro_June2024/F-1982-01141/DOC_0C09000085/C09000085.pdf'),
    officialUrl: stateFoiaCase('F-1982-01141'),
    dataUrl: stateFoiaPdf('DOCUMENTS/FOIA_Micro_June2024/F-1982-01141/DOC_0C09000085/C09000085.pdf'),
    citation:
      'Department of State FOIA Library, case F-1982-01141, document 85, Treaty of Amity and Economic Relations Between the United States of America and Viet-Nam, signed at Saigon, April 3, 1961.',
    summary:
      'Treaty text and related State Department material for the U.S.-Viet-Nam agreement signed at Saigon on April 3, 1961.',
  },
  {
    ...stateFoiaDefaults,
    id: 'state-foia-f199104896-doc11',
    title: 'Memorandum to the Secretary on Ramfis Trujillo',
    date: '1961-02-18',
    container: 'F-1991-04896: Dominican Republic, downfall of Trujillo, democracy in Latin America',
    section: 'Dominican Republic',
    documentNumber: 'F-1991-04896 doc 11',
    topics: ['Latin America', 'Diplomacy'],
    url: stateFoiaPdf('DOCUMENTS/FOIA_Micro_Dec2024_4/F-1991-04896/DOC_0C09000011/C09000011.pdf'),
    officialUrl: stateFoiaCase('F-1991-04896'),
    dataUrl: stateFoiaPdf('DOCUMENTS/FOIA_Micro_Dec2024_4/F-1991-04896/DOC_0C09000011/C09000011.pdf'),
    citation:
      'Department of State FOIA Library, case F-1991-04896, document 11, ARA memorandum to the Secretary, Ramfis Trujillo, February 18, 1961.',
    summary:
      'Assistant Secretary-level memorandum to Secretary Rusk on Ramfis Trujillo and a possible orderly transition in the Dominican Republic.',
  },
  {
    ...stateFoiaDefaults,
    id: 'state-foia-f199104896-doc12',
    title: 'Memorandum of conversation on political and economic conditions in the Dominican Republic',
    date: '1961-02-22',
    container: 'F-1991-04896: Dominican Republic, downfall of Trujillo, democracy in Latin America',
    section: 'Dominican Republic',
    documentNumber: 'F-1991-04896 doc 12',
    topics: ['Latin America', 'Diplomacy'],
    url: stateFoiaPdf('DOCUMENTS/FOIA_Micro_Dec2024_4/F-1991-04896/DOC_0C09000012/C09000012.pdf'),
    officialUrl: stateFoiaCase('F-1991-04896'),
    dataUrl: stateFoiaPdf('DOCUMENTS/FOIA_Micro_Dec2024_4/F-1991-04896/DOC_0C09000012/C09000012.pdf'),
    citation:
      'Department of State FOIA Library, case F-1991-04896, document 12, Memorandum of Conversation, Political and Economic Conditions in the Dominican Republic, February 22, 1961.',
    summary:
      'State Department memorandum of conversation with a U.S. businessman familiar with conditions in the Dominican Republic.',
  },
  {
    ...stateFoiaDefaults,
    id: 'state-foia-f199104896-doc15',
    title: 'Telegram from Ciudad Trujillo on dissidents and regime reaction',
    date: '1961-02-24',
    container: 'F-1991-04896: Dominican Republic, downfall of Trujillo, democracy in Latin America',
    section: 'Dominican Republic',
    documentNumber: 'F-1991-04896 doc 15',
    topics: ['Latin America', 'Diplomacy', 'Intelligence'],
    url: stateFoiaPdf('DOCUMENTS/FOIA_Micro_Dec2024_4/F-1991-04896/DOC_0C09000015/C09000015.pdf'),
    officialUrl: stateFoiaCase('F-1991-04896'),
    dataUrl: stateFoiaPdf('DOCUMENTS/FOIA_Micro_Dec2024_4/F-1991-04896/DOC_0C09000015/C09000015.pdf'),
    citation:
      'Department of State FOIA Library, case F-1991-04896, document 15, Incoming telegram from Ciudad Trujillo, February 24, 1961.',
    summary:
      'Incoming telegram reporting conversations about dissidents, Trujillo regime reactions, and possible U.S. policy implications.',
  },
  {
    ...stateFoiaDefaults,
    id: 'state-foia-f199104896-doc18',
    title: 'Telegram from Ciudad Trujillo on Ramfis Trujillo departure',
    date: '1961-03-03',
    container: 'F-1991-04896: Dominican Republic, downfall of Trujillo, democracy in Latin America',
    section: 'Dominican Republic',
    documentNumber: 'F-1991-04896 doc 18',
    topics: ['Latin America', 'Diplomacy'],
    url: stateFoiaPdf('DOCUMENTS/FOIA_Micro_Dec2024_4/F-1991-04896/DOC_0C09000018/C09000018.pdf'),
    officialUrl: stateFoiaCase('F-1991-04896'),
    dataUrl: stateFoiaPdf('DOCUMENTS/FOIA_Micro_Dec2024_4/F-1991-04896/DOC_0C09000018/C09000018.pdf'),
    citation:
      'Department of State FOIA Library, case F-1991-04896, document 18, Incoming telegram from Ciudad Trujillo, March 3, 1961.',
    summary:
      'Telegram on General Trujillo Jr. (Ramfis) departing the Dominican Republic for New York.',
  },
  {
    ...stateFoiaDefaults,
    id: 'state-foia-f199104896-doc20',
    title: 'Telegram from Ciudad Trujillo on Dominican weekend developments',
    date: '1961-03-06',
    container: 'F-1991-04896: Dominican Republic, downfall of Trujillo, democracy in Latin America',
    section: 'Dominican Republic',
    documentNumber: 'F-1991-04896 doc 20',
    topics: ['Latin America', 'Diplomacy', 'Intelligence'],
    url: stateFoiaPdf('DOCUMENTS/FOIA_Micro_Dec2024_4/F-1991-04896/DOC_0C09000020/C09000020.pdf'),
    officialUrl: stateFoiaCase('F-1991-04896'),
    dataUrl: stateFoiaPdf('DOCUMENTS/FOIA_Micro_Dec2024_4/F-1991-04896/DOC_0C09000020/C09000020.pdf'),
    citation:
      'Department of State FOIA Library, case F-1991-04896, document 20, Incoming telegram from Ciudad Trujillo, March 6, 1961.',
    summary:
      'Telegram to the Secretary of State and other agencies on Dominican Republic developments during the Trujillo crisis.',
  },
  {
    ...stateFoiaDefaults,
    id: 'state-foia-f199104896-doc22',
    title: 'Telegram from Ciudad Trujillo on Dominican Republic developments',
    date: '1961-03-08',
    container: 'F-1991-04896: Dominican Republic, downfall of Trujillo, democracy in Latin America',
    section: 'Dominican Republic',
    documentNumber: 'F-1991-04896 doc 22',
    topics: ['Latin America', 'Diplomacy', 'Intelligence'],
    url: stateFoiaPdf('DOCUMENTS/FOIA_Micro_Dec2024_4/F-1991-04896/DOC_0C09000022/C09000022.pdf'),
    officialUrl: stateFoiaCase('F-1991-04896'),
    dataUrl: stateFoiaPdf('DOCUMENTS/FOIA_Micro_Dec2024_4/F-1991-04896/DOC_0C09000022/C09000022.pdf'),
    citation:
      'Department of State FOIA Library, case F-1991-04896, document 22, Incoming telegram from Ciudad Trujillo, March 8, 1961.',
    summary:
      'March 8 telegram from the U.S. post at Ciudad Trujillo during the Dominican Republic transition crisis.',
  },
  {
    ...stateFoiaDefaults,
    id: 'state-foia-f199104896-doc25',
    title: 'Memorandum of conversation on the current situation in the Dominican Republic',
    date: '1961-03-15',
    container: 'F-1991-04896: Dominican Republic, downfall of Trujillo, democracy in Latin America',
    section: 'Dominican Republic',
    documentNumber: 'F-1991-04896 doc 25',
    topics: ['Latin America', 'Diplomacy'],
    url: stateFoiaPdf('DOCUMENTS/FOIA_Micro_Dec2024_4/F-1991-04896/DOC_0C09000025/C09000025.pdf'),
    officialUrl: stateFoiaCase('F-1991-04896'),
    dataUrl: stateFoiaPdf('DOCUMENTS/FOIA_Micro_Dec2024_4/F-1991-04896/DOC_0C09000025/C09000025.pdf'),
    citation:
      'Department of State FOIA Library, case F-1991-04896, document 25, Memorandum of Conversation, Current Situation in the Dominican Republic, March 15, 1961.',
    summary:
      'Conversation with a former Dominican government official on the current situation in the Dominican Republic.',
  },
  {
    ...stateFoiaDefaults,
    id: 'state-foia-f199104896-doc35',
    title: 'Dispatch from Ciudad Trujillo on the political significance of 1958-1961',
    date: '1961-04-17',
    container: 'F-1991-04896: Dominican Republic, downfall of Trujillo, democracy in Latin America',
    section: 'Dominican Republic',
    documentNumber: 'F-1991-04896 doc 35',
    topics: ['Latin America', 'Diplomacy'],
    url: stateFoiaPdf('DOCUMENTS/FOIA_Micro_Dec2024_4/F-1991-04896/DOC_0C09000035/C09000035.pdf'),
    officialUrl: stateFoiaCase('F-1991-04896'),
    dataUrl: stateFoiaPdf('DOCUMENTS/FOIA_Micro_Dec2024_4/F-1991-04896/DOC_0C09000035/C09000035.pdf'),
    citation:
      'Department of State FOIA Library, case F-1991-04896, document 35, Foreign Service dispatch from Ciudad Trujillo, April 17, 1961.',
    summary:
      "Foreign Service dispatch assessing the political significance of the 1958-1961 period in the Dominican Republic and the Trujillo regime's position.",
  },
  {
    ...nitzeDefaults,
    id: 'nitze-air-force-oral-history-to-page-308',
    title: 'Paul H. Nitze Air Force oral history, transition through page 308',
    date: '',
    displayDate: 'Retrospective interview; covers Jan-Apr 1961',
    documentNumber: 'Air Force oral history to p. 308',
    topics: ['Defense', 'Diplomacy', 'Laos', 'Congo', 'NATO', 'Nuclear'],
    url: nitzePdf('nitze-air-force-oral-history-to-page-308.pdf'),
    officialUrl: nitzePdf('nitze-air-force-oral-history-to-page-308.pdf'),
    dataUrl: nitzePdf('nitze-air-force-oral-history-to-page-308.pdf'),
    citation:
      'Paul H. Nitze, Air Force oral history transcript PDF, transition and Kennedy administration sections through transcript page 308.',
    summary:
      'OCR hits cover Kennedy assigning Nitze early problems, McNamara placing him at ISA, the policy-making vacuum, Laos and Congo in spring 1961, NATO nuclear issues, de Gaulle, and Rusk-McNamara roles.',
  },
  {
    ...nitzeDefaults,
    id: 'nitze-air-force-oral-history-to-page-324',
    title: 'Paul H. Nitze Air Force oral history, Bay of Pigs continuation through page 324',
    date: '',
    displayDate: 'Retrospective interview; covers Apr 1961',
    documentNumber: 'Air Force oral history to p. 324',
    topics: ['Bay of Pigs', 'Cuba', 'Latin America', 'Defense', 'Diplomacy', 'Asia'],
    url: nitzePdf('nitze-air-force-oral-history-to-page-324.pdf'),
    officialUrl: nitzePdf('nitze-air-force-oral-history-to-page-324.pdf'),
    dataUrl: nitzePdf('nitze-air-force-oral-history-to-page-324.pdf'),
    citation:
      'Paul H. Nitze, Air Force oral history transcript PDF, post-Bay of Pigs and related Kennedy administration sections through transcript page 324.',
    summary:
      'Continuation includes Nitze on Kennedy assigning him post-Bay of Pigs policy toward Cuba and Latin America, and moving the work into a State Department task force.',
  },
  {
    ...nitzeDefaults,
    id: 'nitze-air-force-oral-history-to-page-348',
    title: 'Paul H. Nitze Air Force oral history, task-force staff through page 348',
    date: '',
    displayDate: 'Retrospective interview; covers Apr 1961',
    documentNumber: 'Air Force oral history to p. 348',
    topics: ['Bay of Pigs', 'Cuba', 'Latin America', 'Diplomacy'],
    url: nitzePdf('nitze-air-force-oral-history-to-page-348.pdf'),
    officialUrl: nitzePdf('nitze-air-force-oral-history-to-page-348.pdf'),
    dataUrl: nitzePdf('nitze-air-force-oral-history-to-page-348.pdf'),
    citation:
      'Paul H. Nitze, Air Force oral history transcript PDF, later continuation with post-Bay of Pigs task-force staff recollections.',
    summary:
      'OCR hits identify personnel around the post-Bay of Pigs Cuba and Latin America task force, including Richard Goodwin and Adolph Berle.',
  },
  {
    ...nitzeDefaults,
    id: 'nitze-herken-interviews',
    title: 'Paul H. Nitze Herken interviews',
    date: '',
    displayDate: 'Retrospective interview notes; covers 1961',
    documentNumber: 'Herken interviews',
    topics: ['Defense', 'Nuclear', 'USSR'],
    url: nitzePdf('nitze-herken-interviews.pdf'),
    officialUrl: nitzePdf('nitze-herken-interviews.pdf'),
    dataUrl: nitzePdf('nitze-herken-interviews.pdf'),
    citation: 'Paul H. Nitze, Herken interview notes PDF.',
    summary:
      'OCR hits note that JFK appointed Nitze to ISA in 1961 and directed attention to arms control, with later work on test-ban and strategic-limitation issues.',
  },
  {
    ...iscapDefaults,
    id: 'iscap-2014-030-doc-2',
    title: 'Memo re: Chiang Ching-kuo and GRC',
    date: '1961-02-20',
    documentNumber: '2014-030-doc 2',
    dataUrl: iscapPdf(2),
    citation: 'ISCAP Appeal 2014-030, document 2. Memo re: Chiang Ching-kuo and GRC, February 20, 1961.',
    summary: 'Declassified memorandum concerning Chiang Ching-kuo, the Government of the Republic of China, and regional security questions tied to Laos policy.',
    topics: ['Laos', 'Asia', 'Intelligence', 'Defense', 'Diplomacy'],
  },
  {
    ...iscapDefaults,
    id: 'iscap-2014-030-doc-3',
    title: 'Memo to Director from Vientiane',
    date: '1961-03-20',
    documentNumber: '2014-030-doc 3',
    dataUrl: iscapPdf(3),
    citation: 'ISCAP Appeal 2014-030, document 3. Memo to Director from Vientiane, March 20, 1961.',
    summary: 'Declassified Vientiane-origin memorandum to the Director during the Kennedy administration Laos crisis.',
  },
  {
    ...iscapDefaults,
    id: 'iscap-2014-030-doc-4',
    title: 'Cable to Director from Vientiane',
    date: '1961-03-20',
    documentNumber: '2014-030-doc 4',
    dataUrl: iscapPdf(4),
    citation: 'ISCAP Appeal 2014-030, document 4. Cable to Director from Vientiane, March 20, 1961.',
    summary: 'Declassified cable from Vientiane to the Director concerning Laos in March 1961.',
  },
  {
    ...iscapDefaults,
    id: 'iscap-2014-030-doc-5',
    title: 'Cable',
    date: '',
    displayDate: 'Undated (1961)',
    documentNumber: '2014-030-doc 5',
    dataUrl: iscapPdf(5),
    citation: 'ISCAP Appeal 2014-030, document 5. Cable, undated.',
    summary: 'Undated cable released with the ISCAP 2014-030 Laos, 1961 appeal file.',
  },
  {
    ...iscapDefaults,
    id: 'iscap-2014-030-doc-6',
    title: 'Cable to Director from Bangkok',
    date: '1961-04-06',
    documentNumber: '2014-030-doc 6',
    dataUrl: iscapPdf(6),
    citation: 'ISCAP Appeal 2014-030, document 6. Cable to Director from Bangkok, April 6, 1961.',
    summary: 'Declassified Bangkok-origin cable to the Director concerning Laos and regional covert-action issues.',
    topics: ['Laos', 'Asia', 'Intelligence', 'Defense', 'Diplomacy'],
  },
  {
    ...bayOfPigsDefaults,
    id: 'nsarchive-bop-19610211-schlesinger',
    title: 'White House memorandum from Arthur Schlesinger, Jr. to President Kennedy',
    date: '1961-02-11',
    documentNumber: '19610211',
    url: NSARCHIVE_BAY_OF_PIGS_2,
    officialUrl: NSARCHIVE_BAY_OF_PIGS_2,
    dataUrl: bayOfPigsPdf('19610211.pdf'),
    citation: 'White House, Memorandum, Top Secret, Arthur Schlesinger, Jr. to President Kennedy, February 11, 1961.',
    summary: 'Schlesinger warned Kennedy about the political and diplomatic costs of a unilateral invasion of Cuba.',
  },
  {
    ...bayOfPigsDefaults,
    id: 'nsarchive-bop-19610406-cia-discontent',
    title: 'CIA information report on signs of discontent among the Cuban populace',
    date: '1961-04-06',
    documentNumber: '19610406',
    url: NSARCHIVE_BAY_OF_PIGS_3,
    officialUrl: NSARCHIVE_BAY_OF_PIGS_3,
    dataUrl: bayOfPigsPdf('19610406.pdf'),
    citation: 'CIA, Information Report, Signs of Discontent among the Cuban Populace; Activities of the Government to Strengthen Regime, April 6, 1961.',
    summary: 'CIA reporting assessed Cuban public attitudes and regime security activity in the days before the Bay of Pigs invasion.',
  },
  {
    ...bayOfPigsDefaults,
    id: 'nsarchive-bop-19610414-kudryavtsev-guevara-translation',
    title: 'Diary of S. M. Kudryavtsev, record of conversation with Ernesto Guevara (English translation)',
    date: '1961-04-14',
    documentNumber: '19610426-trans',
    url: NSARCHIVE_BAY_OF_PIGS_3,
    officialUrl: NSARCHIVE_BAY_OF_PIGS_3,
    dataUrl: bayOfPigsPdf('19610426-trans.pdf'),
    citation: 'Diary of S. M. Kudryavtsev, Record of Conversation with Ernesto Guevara, April 14, 1961, English translation.',
    summary: 'A Soviet ambassador recorded Che Guevara discussing Cuba, the expected U.S.-backed invasion, and Cuban expectations before the air strikes.',
    topics: ['Bay of Pigs', 'Cuba', 'Latin America', 'USSR', 'Diplomacy'],
  },
  {
    ...bayOfPigsDefaults,
    id: 'nsarchive-bop-19610414-kudryavtsev-guevara-original',
    title: 'Diary of S. M. Kudryavtsev, record of conversation with Ernesto Guevara (Russian original)',
    date: '1961-04-14',
    documentNumber: '19610426',
    url: NSARCHIVE_BAY_OF_PIGS_3,
    officialUrl: NSARCHIVE_BAY_OF_PIGS_3,
    dataUrl: bayOfPigsPdf('19610426.pdf'),
    citation: 'Diary of S. M. Kudryavtsev, Record of Conversation with Ernesto Guevara, April 14, 1961, Russian original.',
    summary: 'Russian-language original of the Kudryavtsev record of conversation with Ernesto Guevara before the Bay of Pigs invasion.',
    topics: ['Bay of Pigs', 'Cuba', 'Latin America', 'USSR', 'Diplomacy'],
  },
  {
    ...bayOfPigsDefaults,
    id: 'nsarchive-bop-196104-chart-plans-training',
    title: 'CIA chart of command organization for plans and training',
    date: '1961-04-01',
    displayDate: 'ca. April 1961',
    documentNumber: 'chart1',
    url: NSARCHIVE_BAY_OF_PIGS_3,
    officialUrl: NSARCHIVE_BAY_OF_PIGS_3,
    dataUrl: bayOfPigsPdf('chart1.pdf'),
    citation: 'CIA, Chart, Secret, Chart of Command Organization for Plans and Training, ca. April 1961.',
    summary: 'Organizational chart for the CIA task force planning and training structure behind the Cuba operation.',
  },
  {
    ...bayOfPigsDefaults,
    id: 'nsarchive-bop-196104-chart-operations',
    title: 'CIA chart of command organization for operations',
    date: '1961-04-01',
    displayDate: 'ca. April 1961',
    documentNumber: 'chart2',
    url: NSARCHIVE_BAY_OF_PIGS_3,
    officialUrl: NSARCHIVE_BAY_OF_PIGS_3,
    dataUrl: bayOfPigsPdf('chart2.pdf'),
    citation: 'CIA, Chart, Secret, Chart of Command Organization for Operations, ca. April 1961.',
    summary: 'Organizational chart for operational command relationships in the CIA-backed Cuba operation.',
  },
  {
    ...bayOfPigsDefaults,
    id: 'nsarchive-bop-19610417-castro-order-translation',
    title: 'Handwritten order from Fidel Castro to Captain Jose R. Fernandez (translation)',
    date: '1961-04-17',
    documentNumber: '19610417-trans',
    url: NSARCHIVE_BAY_OF_PIGS_3,
    officialUrl: NSARCHIVE_BAY_OF_PIGS_3,
    dataUrl: bayOfPigsPdf('19610417-trans.pdf'),
    citation: 'Handwritten Order from Commander-in-Chief Fidel Castro to Captain Jose R. Fernandez, April 17, 1961, English translation.',
    summary: 'Translated Castro battlefield order during the opening day of the Bay of Pigs invasion.',
  },
  {
    ...bayOfPigsDefaults,
    id: 'nsarchive-bop-19610417-castro-order-original',
    title: 'Handwritten order from Fidel Castro to Captain Jose R. Fernandez (Spanish original)',
    date: '1961-04-17',
    documentNumber: '19610417',
    url: NSARCHIVE_BAY_OF_PIGS_3,
    officialUrl: NSARCHIVE_BAY_OF_PIGS_3,
    dataUrl: bayOfPigsPdf('19610417.pdf'),
    citation: 'Handwritten Order from Commander-in-Chief Fidel Castro to Captain Jose R. Fernandez, April 17, 1961, Spanish original.',
    summary: 'Spanish original of Castro battlefield orders during the Bay of Pigs invasion.',
  },
  {
    ...bayOfPigsDefaults,
    id: 'nsarchive-bop-19610418a-castro-message-translation',
    title: 'Handwritten message from Fidel Castro to Julio (Flavio Bravo Pardo), translation',
    date: '1961-04-18',
    documentNumber: '19610418a-trans',
    url: NSARCHIVE_BAY_OF_PIGS_3,
    officialUrl: NSARCHIVE_BAY_OF_PIGS_3,
    dataUrl: bayOfPigsPdf('19610418a-trans.pdf'),
    citation: 'Handwritten Message from Commander-in-Chief Fidel Castro to Julio (Flavio Bravo Pardo), April 18, 1961, English translation.',
    summary: 'Translated Castro handwritten message from the second day of the Bay of Pigs fighting.',
  },
  {
    ...bayOfPigsDefaults,
    id: 'nsarchive-bop-19610418a-castro-message-original',
    title: 'Handwritten message from Fidel Castro to Julio (Flavio Bravo Pardo), Spanish original',
    date: '1961-04-18',
    documentNumber: '19610418a',
    url: NSARCHIVE_BAY_OF_PIGS_3,
    officialUrl: NSARCHIVE_BAY_OF_PIGS_3,
    dataUrl: bayOfPigsPdf('19610418a.pdf'),
    citation: 'Handwritten Message from Commander-in-Chief Fidel Castro to Julio (Flavio Bravo Pardo), April 18, 1961, Spanish original and transcription.',
    summary: 'Spanish original and transcription of Castro message during the Bay of Pigs battle.',
  },
  {
    ...bayOfPigsDefaults,
    id: 'nsarchive-bop-19610418b-castro-order-translation',
    title: 'Handwritten order from Fidel Castro to Captain Jose R. Fernandez (April 18 translation)',
    date: '1961-04-18',
    documentNumber: '19610418b-trans',
    url: NSARCHIVE_BAY_OF_PIGS_3,
    officialUrl: NSARCHIVE_BAY_OF_PIGS_3,
    dataUrl: bayOfPigsPdf('19610418b-trans.pdf'),
    citation: 'Handwritten Order from Commander-in-Chief Fidel Castro to Captain Jose R. Fernandez, April 18, 1961, English translation.',
    summary: 'Translated Castro order issued during the second day of the Bay of Pigs battle.',
  },
  {
    ...bayOfPigsDefaults,
    id: 'nsarchive-bop-19610418b-castro-order-original',
    title: 'Handwritten order from Fidel Castro to Captain Jose R. Fernandez (April 18 Spanish original)',
    date: '1961-04-18',
    documentNumber: '19610418b',
    url: NSARCHIVE_BAY_OF_PIGS_3,
    officialUrl: NSARCHIVE_BAY_OF_PIGS_3,
    dataUrl: bayOfPigsPdf('19610418b.pdf'),
    citation: 'Handwritten Order from Commander-in-Chief Fidel Castro to Captain Jose R. Fernandez, April 18, 1961, Spanish original.',
    summary: 'Spanish original of Castro order issued during the second day of the Bay of Pigs battle.',
  },
  {
    ...bayOfPigsDefaults,
    id: 'nsarchive-bop-19610419-castro-order-translation',
    title: 'Handwritten order from Fidel Castro to Captain Roger Garcia (translation)',
    date: '1961-04-19',
    documentNumber: '19610419-trans',
    url: NSARCHIVE_BAY_OF_PIGS_3,
    officialUrl: NSARCHIVE_BAY_OF_PIGS_3,
    dataUrl: bayOfPigsPdf('19610419-trans.pdf'),
    citation: 'Handwritten Order from Commander-in-Chief Fidel Castro to Captain Roger Garcia, April 19, 1961, English translation.',
    summary: 'Translated Castro order from the final phase of the Bay of Pigs battle.',
  },
  {
    ...bayOfPigsDefaults,
    id: 'nsarchive-bop-19610419-castro-order-original',
    title: 'Handwritten order from Fidel Castro to Captain Roger Garcia (Spanish original)',
    date: '1961-04-19',
    documentNumber: '19610419',
    url: NSARCHIVE_BAY_OF_PIGS_3,
    officialUrl: NSARCHIVE_BAY_OF_PIGS_3,
    dataUrl: bayOfPigsPdf('19610419.pdf'),
    citation: 'Handwritten Order from Commander-in-Chief Fidel Castro to Captain Roger Garcia, April 19, 1961, Spanish original.',
    summary: 'Spanish original of Castro order from the final phase of the Bay of Pigs battle.',
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-20293-goodpaster-football',
    title: 'Memorandum for the Record by Brigadier General Andrew J. Goodpaster, 25 January 1961, Top Secret',
    date: '1961-01-25',
    documentNumber: 'Document 08',
    container: 'Presidential Control of Nuclear Weapons: The Football',
    section: 'Nuclear command and continuity',
    url: nsarchiveDocument('/document/20293-national-security-archive-doc-08-memorandum'),
    officialUrl: nsarchiveDocument('/document/20293-national-security-archive-doc-08-memorandum'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/6895256/National-Security-Archive-Doc-08-Memorandum-for.pdf'),
    citation: 'Memorandum for the Record by Brig. Gen. Andrew J. Goodpaster, January 25, 1961, Top Secret.',
    summary: 'Goodpaster recorded the presidential transition briefing on emergency action documents and the satchel later known as the nuclear football.',
    topics: ['Nuclear', 'Defense'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-15873-vienna-iaea',
    title: 'U.S. Embassy Vienna telegram 1194 to State Department, 26 January 1961, Official Use Only',
    date: '1961-01-26',
    documentNumber: 'Document 37A',
    container: 'IAEA safeguards and nuclear policy documents',
    section: 'IAEA safeguards',
    url: nsarchiveDocument('/document/15873-document-37a-u-s-embassy-vienna-telegram-1194'),
    officialUrl: nsarchiveDocument('/document/15873-document-37a-u-s-embassy-vienna-telegram-1194'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/4116387/Document-37A-U-S-Embassy-Vienna-telegram-1194-to.pdf'),
    citation: 'U.S. Embassy Vienna telegram 1194 to Department of State, January 26, 1961.',
    summary: 'Telegram reporting Board of Governors debate over the International Atomic Energy Agency safeguards document.',
    sourceNote: 'Source: RG 59 Central Decimal Files, 1960-1963, 398.1901-IAEA/1-2661.',
    topics: ['Nuclear', 'Diplomacy'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-21605-rusk-reid-israel',
    title: 'Secretary of State Rusk to President Kennedy, "Your Appointment with Ogden R. Reid, Recently Ambassador to Israel," with memorandum and chronology attached, Secret, Excised copy',
    date: '1961-01-30',
    documentNumber: 'Document 1A',
    container: 'Concerned About Nuclear Weapons Potential, John F. Kennedy Pushed for Inspection of Israel Nuclear Facilities',
    section: 'Israel and Dimona',
    url: nsarchiveDocument('/document/21605-document-1a-secretary-state-rusk-president'),
    officialUrl: nsarchiveDocument('/document/21605-document-1a-secretary-state-rusk-president'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/2806668/Document-1A-Secretary-of-State-Rusk-to-President.pdf'),
    citation: 'Secretary of State Rusk to President Kennedy, January 30, 1961, Secret, excised copy.',
    summary: 'Rusk prepared Kennedy for a briefing with former Ambassador Ogden Reid on U.S.-Israel relations and the Dimona reactor.',
    topics: ['Middle East', 'Nuclear', 'Diplomacy'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-21606-reid-conversation',
    title: 'Memorandum of Conversation, "Ambassador Reid\'s Review of His Conversation with President Kennedy," Secret',
    date: '1961-01-31',
    documentNumber: 'Document 1B',
    container: 'Concerned About Nuclear Weapons Potential, John F. Kennedy Pushed for Inspection of Israel Nuclear Facilities',
    section: 'Israel and Dimona',
    url: nsarchiveDocument('/document/21606-document-1b-memorandum-conversation'),
    officialUrl: nsarchiveDocument('/document/21606-document-1b-memorandum-conversation'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/2806669/Document-1B-Memorandum-of-Conversation.pdf'),
    citation: 'Memorandum of Conversation, Ambassador Reid\'s Review of His Conversation with President Kennedy, January 31, 1961.',
    summary: 'Memorandum recording Ambassador Reid\'s report on his conversation with Kennedy about Israel and Dimona.',
    topics: ['Middle East', 'Nuclear', 'Diplomacy'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-17336-thompson-soviet-cable',
    title: 'Telegram From the Embassy in the Soviet Union to the Department of State',
    date: '1961-02-01',
    documentNumber: 'Document 04',
    container: 'Tommy Thompson - The Kremlinologist',
    section: 'Soviet policy',
    url: nsarchiveDocument('/document/17336-document-04-telegram-embassy'),
    officialUrl: nsarchiveDocument('/document/17336-document-04-telegram-embassy'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/5188887/Document-04-Telegram-From-the-Embassy-in-the.pdf'),
    citation: 'Telegram from the Embassy in the Soviet Union to the Department of State, February 1, 1961.',
    summary: 'Ambassador Llewellyn Thompson assessed Soviet leadership, negotiating posture, and possible U.S. policy approaches for the new administration.',
    sourceNote: 'Source: Foreign Relations of the United States, 1961-1963, Volume V, Soviet Union, Document 20.',
    topics: ['USSR', 'Diplomacy'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-21607-israeli-reactor-suggestion',
    title: 'Assistant Secretary of State for Near Eastern Affairs to Secretary of State, "President\'s Suggestion re Israeli Reactor," Secret',
    date: '1961-02-02',
    documentNumber: 'Document 2A',
    container: 'Concerned About Nuclear Weapons Potential, John F. Kennedy Pushed for Inspection of Israel Nuclear Facilities',
    section: 'Israel and Dimona',
    url: nsarchiveDocument('/document/21607-document-2a-assistant-secretary-state'),
    officialUrl: nsarchiveDocument('/document/21607-document-2a-assistant-secretary-state'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/2806670/Document-2A-Assistant-Secretary-of-State-for.pdf'),
    citation: 'Assistant Secretary of State for Near Eastern Affairs to Secretary of State, President\'s Suggestion re Israeli Reactor, February 2, 1961.',
    summary: 'State Department memorandum following Kennedy\'s suggestion that the United States arrange a visit to Israel\'s Dimona reactor.',
    topics: ['Middle East', 'Nuclear', 'Diplomacy'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-21608-israeli-reactor-memcon',
    title: 'Memorandum of Conversation, "Israeli Reactor," Confidential',
    date: '1961-02-03',
    documentNumber: 'Document 2B',
    container: 'Concerned About Nuclear Weapons Potential, John F. Kennedy Pushed for Inspection of Israel Nuclear Facilities',
    section: 'Israel and Dimona',
    url: nsarchiveDocument('/document/21608-document-2b-memorandum-conversation-israeli'),
    officialUrl: nsarchiveDocument('/document/21608-document-2b-memorandum-conversation-israeli'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/2806671/Document-2B-Memorandum-of-Conversation-Israeli.pdf'),
    citation: 'Memorandum of Conversation, Israeli Reactor, February 3, 1961.',
    summary: 'Memorandum of conversation on Israeli nuclear issues and U.S. interest in inspecting the Dimona reactor.',
    topics: ['Middle East', 'Nuclear', 'Diplomacy'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-21609-rusk-israeli-reactor',
    title: 'Memorandum, Secretary of State Rusk for the President, "Israeli Reactor," Secret',
    date: '1961-02-08',
    documentNumber: 'Document 2C',
    container: 'Concerned About Nuclear Weapons Potential, John F. Kennedy Pushed for Inspection of Israel Nuclear Facilities',
    section: 'Israel and Dimona',
    url: nsarchiveDocument('/document/21609-document-2c-memorandum-secretary-state-rusk'),
    officialUrl: nsarchiveDocument('/document/21609-document-2c-memorandum-secretary-state-rusk'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/2806672/Document-2C-Memorandum-Secretary-of-State-Rusk.pdf'),
    citation: 'Secretary of State Rusk for the President, Israeli Reactor, February 8, 1961.',
    summary: 'Rusk reported to Kennedy on the Israeli reactor question and State Department efforts to arrange inspection access.',
    topics: ['Middle East', 'Nuclear', 'Diplomacy'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-21610-israel-reactor-inspection',
    title: 'Memorandum of Conversation, "Inspection of Israel\'s New Atomic Reactor," Secret',
    date: '1961-02-13',
    documentNumber: 'Document 2D',
    container: 'Concerned About Nuclear Weapons Potential, John F. Kennedy Pushed for Inspection of Israel Nuclear Facilities',
    section: 'Israel and Dimona',
    url: nsarchiveDocument('/document/21610-document-2d-memorandum-conversation'),
    officialUrl: nsarchiveDocument('/document/21610-document-2d-memorandum-conversation'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/2806673/Document-2D-Memorandum-of-Conversation.pdf'),
    citation: 'Memorandum of Conversation, Inspection of Israel\'s New Atomic Reactor, February 13, 1961.',
    summary: 'U.S.-Israeli conversation on arranging an inspection visit to the Dimona reactor.',
    topics: ['Middle East', 'Nuclear', 'Diplomacy'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-17338-thinking-soviet-leadership',
    title: 'The Thinking Of The Soviet Leadership, Cabinet Room, February 11, 1961. Notes on Discussion. Drafted by McGeorge Bundy',
    date: '1961-02-13',
    documentNumber: 'Document 05',
    container: 'Tommy Thompson - The Kremlinologist',
    section: 'Soviet policy',
    url: nsarchiveDocument('/document/17338-document-05-thinking-soviet'),
    officialUrl: nsarchiveDocument('/document/17338-document-05-thinking-soviet'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/5188888/Document-05-The-Thinking-Of-The-Soviet.pdf'),
    citation: 'The Thinking of the Soviet Leadership, notes on Cabinet Room discussion, February 11, 1961, drafted by McGeorge Bundy.',
    summary: 'Notes of a Kennedy meeting with Soviet experts, including Thompson\'s recommendations on U.S. policy toward the Soviet Union.',
    sourceNote: 'Source: Foreign Relations of the United States, 1961-1963, Volume V, Soviet Union, Document 26.',
    topics: ['USSR', 'Berlin', 'Diplomacy'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-28543-holifield-report',
    title: 'Representative Chet Holifield to President Kennedy, enclosing Report on Inspection Trip to NATO Countries, Top Secret, Excised copy',
    date: '1961-02-15',
    documentNumber: 'Document 5',
    container: 'The U.S. Nuclear Presence in Western Europe, 1954-1962, Part II',
    section: 'NATO nuclear custody',
    url: nsarchiveDocument('/document/28543-document-5-representative-chet-holifield-chairman-ad-hoc-subcommittee-president'),
    officialUrl: nsarchiveDocument('/document/28543-document-5-representative-chet-holifield-chairman-ad-hoc-subcommittee-president'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/rdua0b-aismv/05.pdf'),
    citation: 'Representative Chet Holifield to President Kennedy, February 15, 1961, with report on NATO nuclear weapons sites.',
    summary: 'Holifield sent Kennedy a report raising concerns over custody, control, security, and political stability around U.S. nuclear weapons in NATO countries.',
    sourceNote: 'Source: Digital National Security Archive.',
    topics: ['NATO', 'Nuclear', 'Defense', 'Europe'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-28544-holifield-letter',
    title: 'Representative Chet Holifield to President Kennedy, 15 February 1961, no classification markings',
    date: '1961-02-15',
    documentNumber: 'Document 6',
    container: 'The U.S. Nuclear Presence in Western Europe, 1954-1962, Part II',
    section: 'NATO nuclear custody',
    url: nsarchiveDocument('/document/28544-document-6-representative-chet-holifield-chairman-ad-hoc-subcommittee-president'),
    officialUrl: nsarchiveDocument('/document/28544-document-6-representative-chet-holifield-chairman-ad-hoc-subcommittee-president'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/rdua0b-aismv/06.pdf'),
    citation: 'Representative Chet Holifield to President Kennedy, February 15, 1961.',
    summary: 'Full version of Holifield\'s letter to Kennedy, including references to Jupiter missile deployments in Italy and Turkey.',
    sourceNote: 'Source: Digital National Security Archive.',
    topics: ['NATO', 'Nuclear', 'Defense', 'Europe'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-19684-millar-turkey',
    title: 'John Y. Millar to William N. Dale, Counselor, U.S. Embassy Turkey, 15 February 1961, Secret',
    date: '1961-02-15',
    documentNumber: 'Document 11',
    container: 'NATO atomic stockpile and MRBM documents',
    section: 'Turkey and nuclear deployments',
    url: nsarchiveDocument('/document/19684-national-security-archive-doc-11-john-y-millar'),
    officialUrl: nsarchiveDocument('/document/19684-national-security-archive-doc-11-john-y-millar'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/6532125/National-Security-Archive-Doc-11-John-Y-Millar.pdf'),
    citation: 'John Y. Millar to William N. Dale, U.S. Embassy Turkey, February 15, 1961.',
    summary: 'Memorandum on nuclear data transfer and possible Turkish nuclear-capable force arrangements within NATO.',
    sourceNote: 'Source: RG 59, Bureau of European Affairs, Office of European Regional Affairs.',
    topics: ['NATO', 'Nuclear', 'Defense', 'Middle East'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-21611-israel-security-problems',
    title: 'Memorandum of Conversation, "Israel\'s Security and Other Problems," Secret',
    date: '1961-02-16',
    documentNumber: 'Document 2E',
    container: 'Concerned About Nuclear Weapons Potential, John F. Kennedy Pushed for Inspection of Israel Nuclear Facilities',
    section: 'Israel and Dimona',
    url: nsarchiveDocument('/document/21611-document-2e-memorandum-conversation-israel-s'),
    officialUrl: nsarchiveDocument('/document/21611-document-2e-memorandum-conversation-israel-s'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/2806674/Document-2E-Memorandum-of-Conversation-Israel-s.pdf'),
    citation: 'Memorandum of Conversation, Israel\'s Security and Other Problems, February 16, 1961.',
    summary: 'U.S.-Israeli conversation on security problems, Dimona, and regional implications of the Israeli reactor.',
    topics: ['Middle East', 'Nuclear', 'Diplomacy', 'USSR'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-19442-bombay-india-nuclear',
    title: 'U.S. Consul General Bombay Despatch 484 to Department of State, "Possible Indian Desire for Nuclear Weapons Development," Confidential',
    date: '1961-02-20',
    documentNumber: 'Document 05',
    container: 'Nuclear nonproliferation documents',
    section: 'India nuclear policy',
    url: nsarchiveDocument('/document/19442-national-security-archive-doc-05-u-s-consul'),
    officialUrl: nsarchiveDocument('/document/19442-national-security-archive-doc-05-u-s-consul'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/6199561/National-Security-Archive-Doc-05-U-S-Consul.pdf'),
    citation: 'U.S. Consul General Bombay Despatch 484 to Department of State, February 20, 1961.',
    summary: 'Consular reporting on Indian nuclear views and the possibility of nuclear weapons development.',
    topics: ['Nuclear', 'Asia', 'Diplomacy'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-21612-reid-un-telegram',
    title: 'U.S. Mission to the United Nations telegram 2242 to Department of State, "Eyes Only" from Reid to Secretary, Secret',
    date: '1961-02-20',
    documentNumber: 'Document 3A',
    container: 'Concerned About Nuclear Weapons Potential, John F. Kennedy Pushed for Inspection of Israel Nuclear Facilities',
    section: 'Israel and Dimona',
    url: nsarchiveDocument('/document/21612-document-3a-u-s-mission-united-nations'),
    officialUrl: nsarchiveDocument('/document/21612-document-3a-u-s-mission-united-nations'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/2806675/Document-3A-U-S-Mission-to-the-United-Nations.pdf'),
    citation: 'U.S. Mission to the United Nations telegram 2242 to Department of State, February 20, 1961.',
    summary: 'Telegram reporting discussions on arranging a U.S. visit to the Dimona reactor and Israeli political timing.',
    topics: ['Middle East', 'Nuclear', 'Diplomacy', 'United Nations'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-27403-cuba-embargo-questions',
    title: 'NSC memorandum, "Memorandum for the Secretary of State," February 21, 1961',
    date: '1961-02-21',
    documentNumber: 'Document 4',
    container: 'Cuba Embargoed: U.S. Trade Sanctions Turn Sixty',
    section: 'Cuba embargo policy',
    url: nsarchiveDocument('/document/27403-document-4-nsc-memorandum-memorandum-secretary-state-february-21-1961'),
    officialUrl: nsarchiveDocument('/document/27403-document-4-nsc-memorandum-memorandum-secretary-state-february-21-1961'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/Embargo4JFKquestions.pdf'),
    citation: 'NSC Memorandum for the Secretary of State, February 21, 1961.',
    summary: 'Kennedy, through McGeorge Bundy, asked Rusk whether expanding the Cuba embargo would save exchange, hurt Castro, and serve the public interest.',
    topics: ['Cuba', 'Latin America', 'Diplomacy'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-28546-fowler-jcs-debrief',
    title: 'R.D. Fowler memorandum for the record, "Debrief of President\'s Meeting with JCS on 23 Feb 1961," Top Secret',
    date: '1961-02-24',
    documentNumber: 'Document 8',
    container: 'The U.S. Nuclear Presence in Western Europe, 1954-1962, Part II',
    section: 'Nuclear command and NATO',
    url: nsarchiveDocument('/document/28546-document-8-rd-fowler-office-chief-naval-operations-memorandum-record-debrief-presi'),
    officialUrl: nsarchiveDocument('/document/28546-document-8-rd-fowler-office-chief-naval-operations-memorandum-record-debrief-presi'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/rdua0b-aismv/08.pdf'),
    citation: 'R.D. Fowler, Memorandum for the Record, Debrief of President\'s Meeting with JCS on February 23, 1961.',
    summary: 'Fowler recorded Kennedy\'s questions to the Joint Chiefs about nuclear weapons control, presidential authority, and the Holifield report.',
    sourceNote: 'Source: U.S. Navy Heritage and History Command, Archives, Double-Zero Files 1966.',
    topics: ['NATO', 'Nuclear', 'Defense'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-27404-cuba-embargo-rusk',
    title: 'State Department memorandum, "Questions Arising from Senator Smathers Recommendation that Remaining Exports from Cuba to the United States by Embargoed," Secret',
    date: '1961-02-24',
    documentNumber: 'Document 5',
    container: 'Cuba Embargoed: U.S. Trade Sanctions Turn Sixty',
    section: 'Cuba embargo policy',
    url: nsarchiveDocument('/document/27404-document-5-state-department-memorandum-questions-arising-senator-smathers'),
    officialUrl: nsarchiveDocument('/document/27404-document-5-state-department-memorandum-questions-arising-senator-smathers'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/Embargo5Ruskresponse61.pdf'),
    citation: 'State Department memorandum on Senator Smathers recommendation concerning Cuba exports, February 24, 1961.',
    summary: 'Rusk answered Kennedy\'s questions on the merits and public-interest case for a fuller trade embargo against Cuba.',
    topics: ['Cuba', 'Latin America', 'Diplomacy'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-21613-us-israel-dimona',
    title: 'Memorandum of Conversation, "U.S.-Israeli Relations - The Dimona Reactor," Confidential',
    date: '1961-02-26',
    documentNumber: 'Document 3B',
    container: 'Concerned About Nuclear Weapons Potential, John F. Kennedy Pushed for Inspection of Israel Nuclear Facilities',
    section: 'Israel and Dimona',
    url: nsarchiveDocument('/document/21613-document-3b-memorandum-conversation-u-s'),
    officialUrl: nsarchiveDocument('/document/21613-document-3b-memorandum-conversation-u-s'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/2806676/Document-3B-Memorandum-of-Conversation-U-S.pdf'),
    citation: 'Memorandum of Conversation, U.S.-Israeli Relations - The Dimona Reactor, February 26, 1961.',
    summary: 'Memorandum of conversation on U.S.-Israeli relations and the unresolved question of access to Dimona.',
    topics: ['Middle East', 'Nuclear', 'Diplomacy'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-28542-pender-stockpile-custody',
    title: 'J.H. Pender, "State Department Role in Atomic Weapons Stockpile Custodial Arrangements," Secret',
    date: '1961-02-28',
    documentNumber: 'Document 4',
    container: 'The U.S. Nuclear Presence in Western Europe, 1954-1962, Part II',
    section: 'NATO nuclear custody',
    url: nsarchiveDocument('/document/28542-document-4-jh-pender-lsfp-assistant-legal-adviser-special-functional-problems-state'),
    officialUrl: nsarchiveDocument('/document/28542-document-4-jh-pender-lsfp-assistant-legal-adviser-special-functional-problems-state'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/rdua0b-aismv/04.pdf'),
    citation: 'J.H. Pender, State Department Role in Atomic Weapons Stockpile Custodial Arrangements, February 28, 1961.',
    summary: 'State Department legal memorandum on U.S. knowledge and responsibility for custody arrangements at nuclear weapons sites in Europe.',
    sourceNote: 'Source: Digital National Security Archive.',
    topics: ['NATO', 'Nuclear', 'Defense', 'Europe'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-28549-kohler-atomic-stockpile',
    title: 'Foy D. Kohler to the Secretary, "Executive Branch Position on Further Negotiation of Pending Atomic Cooperation and Atomic Stockpile Agreements," Secret',
    date: '1961-02-28',
    documentNumber: 'Document 11',
    container: 'The U.S. Nuclear Presence in Western Europe, 1954-1962, Part II',
    section: 'NATO atomic stockpile',
    url: nsarchiveDocument('/document/28549-document-11-eur-foy-d-kohler-secretary-executive-branch-position-further-negotiation'),
    officialUrl: nsarchiveDocument('/document/28549-document-11-eur-foy-d-kohler-secretary-executive-branch-position-further-negotiation'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/rdua0b-aismv/11.pdf'),
    citation: 'Foy D. Kohler to the Secretary, February 28, 1961, on atomic cooperation and stockpile agreements.',
    summary: 'Kohler briefed Rusk on negotiations involving NATO atomic information and stockpile arrangements with European allies.',
    sourceNote: 'Source: RG 59, Central Decimal Files, 611.657.',
    topics: ['NATO', 'Nuclear', 'Defense', 'Europe'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-21614-rusk-israeli-reactor',
    title: 'Memorandum by Secretary Rusk to President Kennedy, "Israeli Reactor," with memo from Jones to Rusk attached, Confidential',
    date: '1961-03-03',
    documentNumber: 'Document 3C',
    container: 'Concerned About Nuclear Weapons Potential, John F. Kennedy Pushed for Inspection of Israel Nuclear Facilities',
    section: 'Israel and Dimona',
    url: nsarchiveDocument('/document/21614-document-3c-memorandum-secretary-rusk'),
    officialUrl: nsarchiveDocument('/document/21614-document-3c-memorandum-secretary-rusk'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/2806677/Document-3C-Memorandum-by-Secretary-Rusk-to.pdf'),
    citation: 'Secretary Rusk to President Kennedy, Israeli Reactor, March 3, 1961.',
    summary: 'Rusk updated Kennedy on Israeli reactor inspection discussions and attached a Jones memorandum on the same issue.',
    topics: ['Middle East', 'Nuclear', 'Diplomacy'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-21615-dimona-memcon',
    title: 'Memorandum of Conversation, "Dimona Reactor," Secret',
    date: '1961-03-13',
    documentNumber: 'Document 3D',
    container: 'Concerned About Nuclear Weapons Potential, John F. Kennedy Pushed for Inspection of Israel Nuclear Facilities',
    section: 'Israel and Dimona',
    url: nsarchiveDocument('/document/21615-document-3d-memorandum-conversation-dimona'),
    officialUrl: nsarchiveDocument('/document/21615-document-3d-memorandum-conversation-dimona'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/2806678/Document-3D-Memorandum-of-Conversation-Dimona.pdf'),
    citation: 'Memorandum of Conversation, Dimona Reactor, March 13, 1961.',
    summary: 'Memorandum of conversation continuing U.S.-Israeli exchanges over access to the Dimona reactor.',
    topics: ['Middle East', 'Nuclear', 'Diplomacy'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-23731-norstad-volkel',
    title: 'Memorandum for the Record by Major H.F. Williams, "General Norstad\'s Visit to [Volkel Air Force Base] on 29 March 1961," Secret',
    date: '1961-03-19',
    documentNumber: 'Document 09',
    container: 'The U.S. Nuclear Presence in Western Europe, 1954-1962, Part II',
    section: 'NATO nuclear storage',
    url: nsarchiveDocument('/document/23731-memorandum-record-major-h-f-williams-executive-assistant-saceur-general-norstad-s'),
    officialUrl: nsarchiveDocument('/document/23731-memorandum-record-major-h-f-williams-executive-assistant-saceur-general-norstad-s'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/qvvm8h-lx1ik/09.pdf'),
    citation: 'Major H.F. Williams, Memorandum for the Record on General Norstad\'s visit to Volkel Air Force Base, March 1961.',
    summary: 'Report on SACEUR General Norstad\'s briefing at a nuclear storage site in the Netherlands under NATO atomic stockpile arrangements.',
    sourceNote: 'Source: Dwight D. Eisenhower Library, Lauris Norstad Papers.',
    topics: ['NATO', 'Nuclear', 'Defense', 'Europe'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-28362-cia-elint-3025',
    title: 'Office of Scientific Intelligence, CIA, ELINT Report of Mission 3025, March 27, 1961, Top Secret',
    date: '1961-03-27',
    documentNumber: 'Document 4',
    container: 'CIA signals intelligence and reconnaissance documents',
    section: 'Laos, Vietnam, and electronic intelligence',
    url: nsarchiveDocument('/document/28362-document-4-office-scientific-intelligence-cia-elint-report-mission-3025-march-27'),
    officialUrl: nsarchiveDocument('/document/28362-document-4-office-scientific-intelligence-cia-elint-report-mission-3025-march-27'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/rd5srg-2je8j/ciasignals_04.pdf'),
    citation: 'Office of Scientific Intelligence, CIA, ELINT Report of Mission 3025, March 27, 1961.',
    summary: 'CIA report on U-2 electronic intelligence collection over the South China Sea, Laos, South Vietnam, and North Vietnam.',
    sourceNote: 'Source: CREST, NARA, College Park.',
    topics: ['Laos', 'Vietnam', 'Asia', 'Intelligence', 'Defense'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-21616-dimona-memcon',
    title: 'Memorandum of Conversation, "Dimona Reactor," Secret',
    date: '1961-03-28',
    documentNumber: 'Document 3E',
    container: 'Concerned About Nuclear Weapons Potential, John F. Kennedy Pushed for Inspection of Israel Nuclear Facilities',
    section: 'Israel and Dimona',
    url: nsarchiveDocument('/document/21616-document-3e-memorandum-conversation-dimona'),
    officialUrl: nsarchiveDocument('/document/21616-document-3e-memorandum-conversation-dimona'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/2806679/Document-3E-Memorandum-of-Conversation-Dimona.pdf'),
    citation: 'Memorandum of Conversation, Dimona Reactor, March 28, 1961.',
    summary: 'Memorandum of conversation as U.S. officials pressed for an inspection visit to the Dimona reactor.',
    topics: ['Middle East', 'Nuclear', 'Diplomacy'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-21617-rusk-dimona-history',
    title: 'Memorandum from Secretary Rusk to President Kennedy, "Dimona Reactor in Israel," with history attached, Secret',
    date: '1961-03-30',
    documentNumber: 'Document 3F',
    container: 'Concerned About Nuclear Weapons Potential, John F. Kennedy Pushed for Inspection of Israel Nuclear Facilities',
    section: 'Israel and Dimona',
    url: nsarchiveDocument('/document/21617-document-3f-memorandum-secretary-rusk'),
    officialUrl: nsarchiveDocument('/document/21617-document-3f-memorandum-secretary-rusk'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/2806680/Document-3F-Memorandum-from-Secretary-Rusk-to.pdf'),
    citation: 'Secretary Rusk to President Kennedy, Dimona Reactor in Israel, March 30, 1961.',
    summary: 'Rusk sent Kennedy an update and background history on U.S. interest in Israel\'s atomic energy activities.',
    topics: ['Middle East', 'Nuclear', 'Diplomacy'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-15876-iaea-safeguards',
    title: 'International Atomic Energy Agency, "The Agency\'s Safeguards," INFCIRC/26',
    date: '1961-03-30',
    documentNumber: 'Document 37D',
    container: 'IAEA safeguards and nuclear policy documents',
    section: 'IAEA safeguards',
    url: nsarchiveDocument('/document/15876-document-37d-international-atomic-energy-agency'),
    officialUrl: nsarchiveDocument('/document/15876-document-37d-international-atomic-energy-agency'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/4116390/Document-37D-International-Atomic-Energy-Agency.pdf'),
    citation: 'International Atomic Energy Agency, The Agency\'s Safeguards, INFCIRC/26, March 30, 1961.',
    summary: 'IAEA safeguards document setting out early international nuclear safeguards policy.',
    sourceNote: 'Source: International Atomic Energy Agency.',
    topics: ['Nuclear', 'Diplomacy'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-21618-us-visit-dimona',
    title: 'Memorandum of Conversation, "U.S. Visit to Dimona Reactor Site," Secret',
    date: '1961-04-10',
    documentNumber: 'Document 4A',
    container: 'Concerned About Nuclear Weapons Potential, John F. Kennedy Pushed for Inspection of Israel Nuclear Facilities',
    section: 'Israel and Dimona',
    url: nsarchiveDocument('/document/21618-document-4a-memorandum-conversation-u-s-visit'),
    officialUrl: nsarchiveDocument('/document/21618-document-4a-memorandum-conversation-u-s-visit'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/2806681/Document-4A-Memorandum-of-Conversation-U-S-Visit.pdf'),
    citation: 'Memorandum of Conversation, U.S. Visit to Dimona Reactor Site, April 10, 1961.',
    summary: 'Memorandum on Israeli agreement and conditions for a quiet U.S. visit to the Dimona reactor site.',
    topics: ['Middle East', 'Nuclear', 'Diplomacy'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-21619-harman-appointment',
    title: 'Memorandum by Assistant Secretary Jones to Secretary of State Rusk, "Your Appointment with Israeli Ambassador Harman," Secret',
    date: '1961-04-11',
    documentNumber: 'Document 4B',
    container: 'Concerned About Nuclear Weapons Potential, John F. Kennedy Pushed for Inspection of Israel Nuclear Facilities',
    section: 'Israel and Dimona',
    url: nsarchiveDocument('/document/21619-document-4b-memorandum-assistant-secretary'),
    officialUrl: nsarchiveDocument('/document/21619-document-4b-memorandum-assistant-secretary'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/2806682/Document-4B-Memorandum-by-Assistant-Secretary.pdf'),
    citation: 'Assistant Secretary Jones to Secretary Rusk, Your Appointment with Israeli Ambassador Harman, April 11, 1961.',
    summary: 'Jones briefed Rusk before meeting Ambassador Harman, as Ben-Gurion sought a Kennedy meeting while U.S. officials insisted on a Dimona visit.',
    topics: ['Middle East', 'Nuclear', 'Diplomacy'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-20816-khrushchev-vostok',
    title: 'Nikita S. Khrushchev, "Proposals in connection with the launch of the Vostok spacecraft with Yuri Gagarin," April 11, 1961',
    date: '1961-04-11',
    documentNumber: 'Document 1',
    container: 'U.S.-Soviet Cooperation in Outer Space, Part 1',
    section: 'Space policy and Soviet-U.S. relations',
    url: nsarchiveDocument('/document/20816-01'),
    officialUrl: nsarchiveDocument('/document/20816-01'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/20604732/01.pdf'),
    citation: 'Nikita S. Khrushchev, Proposals in connection with the launch of Vostok with Yuri Gagarin, April 11, 1961.',
    summary: 'Translated Soviet document prepared around Gagarin\'s flight, providing context for Kennedy\'s space-cooperation message to Khrushchev.',
    sourceNote: 'Source: Russian State Archive of Contemporary History.',
    topics: ['USSR', 'Nuclear', 'Diplomacy'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-20832-kennedy-khrushchev-space',
    title: 'White House Press Secretary Telegram, John F. Kennedy to Nikita S. Khrushchev, April 12, 1961',
    date: '1961-04-12',
    documentNumber: 'Document 2',
    container: 'U.S.-Soviet Cooperation in Outer Space, Part 1',
    section: 'Space policy and Soviet-U.S. relations',
    url: nsarchiveDocument('/document/20832-02'),
    officialUrl: nsarchiveDocument('/document/20832-02'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/20606509/02.pdf'),
    citation: 'White House Press Secretary Telegram, John F. Kennedy to Nikita S. Khrushchev, April 12, 1961.',
    summary: 'Kennedy congratulated Khrushchev on Gagarin\'s flight and expressed interest in U.S.-Soviet cooperation in outer space.',
    sourceNote: 'Source: John F. Kennedy Presidential Library.',
    topics: ['USSR', 'Diplomacy'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-21620-us-visit-dimona',
    title: 'Memorandum of Conversation, "U.S. Visit to Dimona," Secret',
    date: '1961-04-17',
    documentNumber: 'Document 5A',
    container: 'Concerned About Nuclear Weapons Potential, John F. Kennedy Pushed for Inspection of Israel Nuclear Facilities',
    section: 'Israel and Dimona',
    url: nsarchiveDocument('/document/21620-document-5a-memorandum-conversation-u-s-visit'),
    officialUrl: nsarchiveDocument('/document/21620-document-5a-memorandum-conversation-u-s-visit'),
    dataUrl: nsarchiveDocument('/sites/default/files/documents/2806683/Document-5A-Memorandum-of-Conversation-U-S-Visit.pdf'),
    citation: 'Memorandum of Conversation, U.S. Visit to Dimona, April 17, 1961.',
    summary: 'Memorandum on secrecy, timing, and conditions for the U.S. visit to Dimona before Kennedy met Ben-Gurion.',
    topics: ['Middle East', 'Nuclear', 'Diplomacy'],
  },
  {
    ...nsarchiveDefaults,
    id: 'nsarchive-29393-kozlov-suslov-bravo',
    title: 'Memorandum of Conversation between Frol Kozlov, Mikhail Suslov and Flavio Bravo, Moscow',
    date: '1961-03-03',
    documentNumber: 'Document 3',
    container: 'The Cuban Missile Crisis @ 60: Getting to Know the Cubans, Part Two',
    section: 'Cuba and Soviet relations',
    url: nsarchiveDocument('/document/29393-document-3-memorandum-conversation-between-frol-kozlov-mikhail-suslov-and-flavio'),
    officialUrl: nsarchiveDocument('/document/29393-document-3-memorandum-conversation-between-frol-kozlov-mikhail-suslov-and-flavio'),
    dataUrl: nsarchiveDocument('/sites/default/files/2022-11/1961-03-03-Bravo-Flavio-Kozlov-memcon.pdf'),
    citation: 'Memorandum of Conversation between Frol Kozlov, Mikhail Suslov and Flavio Bravo, Moscow, March 3, 1961.',
    summary: 'Cuban communist leader Flavio Bravo briefed Soviet officials on the Cuban political and military situation before the Bay of Pigs invasion.',
    sourceNote: 'Source: Archive of the President of the Russian Federation; translation by Adam Mayle and Svetlana Savranskaya.',
    topics: ['Cuba', 'Latin America', 'USSR', 'Diplomacy', 'Bay of Pigs'],
  },
];
